---
title: "Publication record"
output:
  rmarkdown::html_vignette:
    toc: true
    fig_caption: true
fontsize: 11pt
documentclass: article
vignette: >
  %\VignetteIndexEntry{Publication record}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

This vignette contains a list of publications that have cited or used the _prioritizr R_ package. It may be useful if you are looking for case studies or examples of specific functionality. We would love to hear from you if you have used the package in your own work. Please [post an issue on GitHub](https://github.com/prioritizr/prioritizr/issues/new) so we can add your work to this list.

## Research articles

### 2025
* Binley AD, Hanson JO, Robinson OJ, Golet GH, and Bennett JR (2025) Quantifying the value of participatory science data for conservation decision‐making. _Journal of Applied Ecology_, **In press**: DOI&#58;10.1111/1365-2664.14863.
* Carroll KA, Pidgeon AM, Elsen P, Farwell L, and Radeloff VC (2025) Biodiversity metric selection and their applications for spatial conservation planning. _Diversity and Distributions_, **31**: e13952.
* Frisk CA and Hanslin HM (2025) Optimizing plant species composition of green roofs for ecological functionality and biodiversity conservation. _Urban Ecosystems_, **28**: 12.
* Matus-Olivares C, Carrasco J, Weintraub A, and Lisón F (2025) From virtue to sin: Is the installation of bat boxes an effective conservation measure or a potential pitfall for vulnerable bat species? _Journal for Nature Conservation_, **83**: 126775.
* Parsch C, Denelle P, Bless E, and Kreft H (2025) Diverging conservation priorities across New Guinea: Conflicts and opportunities. _Global Ecology and Conservation_, **In press**: e03549.

### 2024

* Andrello M and Manel S (2024) Evaluating different approaches to integrate genome-wide genetic diversity in spatial conservation prioritization. _Biological Conservation_, **292**: 110533.
* Berio Fortini L, Leopold CR, Amidon F, Leopold DR, Fretz JS, Jacobi JD, Mehrhoff L, Price JP, Duvall F, Keir M, Oppenheimer H, Weisenberger L, and Sutter R (2024) Advancing at‐risk species recovery planning in an era of rapid ecological change with a transparent, flexible, and expert‐engaged approach. _Conservation Biology_, **In press**: e14421.
* d'Albertas F, Sparovek G, Pinto L-FG, Hohlenwerger C, and Metzger J-P (2024) Yield increases mediated by pollination and carbon payments can offset restoration costs in coffee landscapes. _One Earth_, **7**: 110--122.
* Doxa A, Adam C, Nagkoulis N, Mazaris AD, Katsanevakis S (2025) prior3D: An R package for three-dimensional conservation prioritization. _Ecological Modelling_, **499**: 110919.
* Du Z, Li L, Liang J, Kang B, Meng W, and Li H (2024) National scale biodiversity conservation priorities based on integrated multiple vulnerability features in China. _Ecological Indicators_, **160**: 111914.
* Finucci B, Pacoureau N, Rigby CL, Matsushiba JH, Faure-Beaulieu N, Sherman CS, VanderWright WJ, Jabado RW, Charvet P, Mejía-Falla PA, Navia AF, Derrick DH, Kyne PM, Pollom RA, Walls RHL, Herman KB, Kinattumkara B, Cotton CF, Cuevas J-M, Daley RK, Dharmadi, Ebert DA, Fernando D, Fernando SMC, Francis MP, Huveneers C, Ishihara H, Kulka DW, Leslie RW, Neat F, Orlov AM, Rincon G, Sant GJ, Volvenko IV, Walker TI, Simpfendorfer CA, and Dulvy NK (2024) Fishing for oil and meat drives irreversible defaunation of deepwater sharks and rays. _Science_, **383**: 1135--1141.
* Fourchault L, Dahdouh-Guebas F, Dunn DC, Everett JD, Hanson JO, Buenafe KCV, Neubert S, Dabalà A, Yapa KKAS, Cannicci S, and Richardson AJ (2024) Generating affordable protection of high seas biodiversity through cross-sectoral spatial planning. _One Earth_, **7**: 253--264.
* Gopalakrishna T, Visconti P, Lomax G, Boere E, Malhi Y, Roy PS, Joshi PK, Fedele G, and Yowargana P (2024) Optimizing restoration: A holistic spatial approach to deliver Nature's Contributions to People with minimal tradeoffs and maximal equity. _Proceedings of the National Academy of Sciences_, **121**: e2402970121.
* Hanson JO, Schuster R, Strimas-Mackey M, Morrell N, Edwards BPM, Arcese P, Bennett JR, and Possingham HP (2024). Systematic conservation prioritization with the prioritizr R package. _Conservation Biology_, **39**: e14376.
* Kim J, Shin W, Kim S, Choe H, Tanaka T, and Song Y (2024) Use of ecosystem services and land ownership to prioritize conservation areas on Jeju Island, Republic of Korea. _Ecosystem Services_, **66**: 101605.
* Mannocci L, Derville S, Seguin R, and Mouillot D (2024) Aerial video surveys and spatial prioritization reveal conservation opportunities for endangered dugongs in New Caledonia. _Aquatic Conservation: Marine and Freshwater Ecosystems_, **34**: e4237.
* Nagkoulis N, Papazekou M, Katsanevakis S, and Mazaris A (2024) Spatial conservation planning: Proposing clustering methods to improve connectivity protection. *Methods in Ecology and Evolution*, **16**: 377--387.
* Neugarten RA, Chaplin-Kramer R, Sharp RP, Schuster R, Strimas-Mackey M, Roehrdanz PR, Mulligan M, van Soesbergen A, Hole D, Kennedy CM, Oakleaf JR, Johnson JA, Kiesecker J, Polasky S, Hanson JO, and Rodewald AD (2024) Mapping the planet's critical areas for biodiversity and nature's contributions to people. _Nature Communications_, **15**: 261.
* Schleimer A, Cantú‐Salazar L, Luttringer A, and Frantz AC (2024) Spatial prioritisation for crested newt conservation in Luxembourg: Insights from population genetics and species distribution modelling. _Ecological Solutions and Evidence_, **5**: e12310.
* von Takach B, Cameron SF, Cremona T, Eldridge MDB, Fisher DO, Hohnen R, Jolly CJ, Kelly E, Phillips BL, Radford IJ, Rick K, Spencer PBS, Trewella GJ, Umbrello LS, and Banks SC (2024) Conservation prioritisation of genomic diversity to inform management of a declining mammal species. _Biological Conservation_, **291**: 110467.
* Yang L, Xu W, Chen T, Fan Y, and Fan P (2024) Integrating natural disasters into protected area designing for global primate conservation under climate change. _Geography and Sustainability_, **6**: 100242.
* Zucconi MG, Opazo F,and  Navarrete SA (2024) Assessing the Efficiency of the Marine Protected Area Systems in the Southeastern Pacific. *Aquatic Conservation: Marine and Freshwater Ecosystems*, **34**: e70032.

### 2023

* Algador D (2022) Effective conservation planning of Iberian amphibians based on a regionalization of climate driven range shifts. _Conservation Biology_, **37**: e14026.
* Alves F, Banks SC, Edworthy M, Stojanovic D, Langmore NE, and Heinsohn R (2023) Using conservation genetics to prioritise management options for an endangered songbird. _Heredity_, **130**: 289--301.
* Aschi F, Dekker SC, van Vuuren DP, Bogaart PW, Rijsdijk KF, and van Loon EE (2023) Costs and benefits of protecting linear landscape elements: Applying systematic conservation planning on a case study in the Netherlands. _Journal of Environmental Management_, **348**: 119262.
* Boussarie G, Kopp D, Lavialle G, Mouchet M, and Morfin M (2023) Marine spatial planning to solve increasing conflicts at sea: A framework for prioritizing offshore windfarms and marine protected areas. _Journal of Environmental Management_, **339**: 117857.
* Buenafe KCV, Dunn DC, Everett JD, Brito-Morales I, Schoeman DS, Hanson JO, Dabalà A, Neubert S, Cannicci S, Kaschner K, and Richardson AJ (2023) A metric-based framework for climate-smart conservation planning. _Ecological Applications_, **33**: e2852.
* Chowdhury S, Fuller RA, Rokonuzzaman M, Alam S, Das P, Siddika A, Ahmed S, Labi MM, Chowdhury SU, Mukul SA, Bohm M, and Hanson JO (2023) Insights from citizen science reveal priority areas for conserving biodiversity in Bangladesh. _One Earth_, **6**: 1315--1325.
* Dabalà A, Dahdouh-Guebas F, Dunn DC, Everett JD, Lovelock CE, Hanson JO, Buenafe KVC, Neubert S, and Richardson AJ (2023) Priority areas to protect mangroves and maximise ecosystem services. _Nature Communications_, 14: 5863.
* Engert J and Laurance SG (2023) Economics and optics influence funding for ecological restoration in a nation-wide program. _Environmental Research Letters_, **18**: 054020.
* Faure-Beaulieu N, Lombard AT, Olbers J, Goodall V, da Silva C, Daly R, Jordaan G, Kerwath SE, Kock A, Mann BQ, Murray TS, Albano P, Cliff G, dos Santos NA, Gennari E, Hammerschlag N, Bester-van der Merwe AE, Watson R, Andreotti S, Bernard ATF, Cowley PD, De Vos L, Drobniewska N, Elston C, Fallows C, Rogers TD, Smith G, van Staden M, de Villiers P, Paulet TG, and Harris J (2023). A systematic conservation plan identifying critical areas for improved chondrichthyan protection in South Africa. _Biological Conservation_, **284**: 110163.
* Finn RJR, Chalifour L, Gergel SE, Hinch SG, Scott DC, and Martin TG (2023) Using systematic conservation planning to inform restoration of freshwater habitat and connectivity for salmon. _Conservation Science and Practice_, **5**: e12973.
* Giménez J, Waggitt JJ, and Jessopp M (2023) Identification of priority cetacean areas in the north‐east Atlantic using systematic conservation planning. _Aquatic Conservation: Marine and Freshwater Ecosystems_, **33**: 1571--1579.
* Li Y, Zhao X, Xia M, and Hou H (2023). Genetic and epigenetic variation of _Trapa bispinosa_ under slope gradient: A case study in a subtropical freshwater lake. _Aquatic Botany_, **188**: 103679.
* Li Y, Xia M, Zhao X, and Hou H (2023) Water temperature and chlorophyll a density drive the genetic and epigenetic variation of _Vallisneria natans_ across a subtropical freshwater lake. _Ecology and Evolution_, **13**: e10434.
* Liczner AR, Schuster R, Richardson LL, and Colla SR (2023) Identifying conservation priority areas for North American bumble bee species in Canada under current and future climate scenarios. _Conservation Science and Practice_, **5**: e12994.
* Massante JC, de Castro AF, de Medeiros Sarmento PS, da Silva GM, Caldeira CF, Ramos S, and Gastauer M (2023) Species selection for optimizing mine land rehabilitation: Integrating functional traits with the minimum set prioritization technique. _Ecological Engineering_, **194**: 107039.
* Rick K, Byrne M, Cameron S, Cooper SJB, Dunlop J, Hill B, Lohr C, Mitchell NJ, Moritz C, Travouillon KJ, von Takach B, and Ottewell K (2023). Population genomic diversity and structure in the golden bandicoot: a history of isolation, extirpation, and conservation. _Heredity_, **131**: 374--386.
* Nielsen ES, Beger M, Henriques R, and von der Heyden S (2023) Integrating environmental, evolutionary, and socioeconomic vulnerability to future-proof coastal conservation planning. _Biological Conservation_, **286**: 110302.
* Nogales J, Rogéliz-Prada C, Cañon MA, and Vargas-Luna A (2023) An integrated methodological framework for the durable conservation of freshwater ecosystems: a case study in Colombia’s Caquetá River basin. _Frontiers in Environmental Science_, **11**: 1264392.
* Shen X, Liu M, Hanson JO, Wang J, Locke H, Watson JEM, Ellis EC, Li S, and Ma K (2023) Countries' differentiated responsibilities to fulfill area-based conservation targets of the Kunming-Montreal Global Biodiversity Framework. _One Earth_, **6**:  548--559.
* Sievers M, Brown CJ, McGowan J, Turschwell MP, Buelow CA, Holgate B, Pearson, RM, Adame MF, Andradi-Brown DA, Arnell A, Mackey BG, zu Ermgassen PSE, Gosling, J, McOwen CJ, Worthington TA, and Connolly RM (2023) Co-occurrence of biodiversity, carbon storage, coastal protection, and fish and invertebrate production to inform global mangrove conservation planning. _Science of The Total Environment_, **904**: 166357.
* Tack JD, Jakes AF, Jones PF, Hebblewhite M, Naugle DE, Doherty KE, Sather M K, Martin BH, and Pritchert R (2023) Grassland intactness outcompetes species as a more efficient surrogate in conservation design. _Conservation Science and Practice_, **5**: e13020.
* von Takach B, Sargent H, Penton CE, Rick K, Murphy BP, Neave G, Davies HF, Hill BM, and Banks SC (2023) Population genomics and conservation management of the threatened black-footed tree-rat (_Mesembriomys gouldii_) in northern Australia. _Heredity_, **130**: 278--288.
* van Lanen, NJ, Shyvers JE, Duchardt CJ, and Aldridge CL (2023) A multi-ecosystem prioritization framework to balance competing habitat conservation needs of multiple species in decline. _Landscape Ecology_, **38**: 2795--2813.
* Vyas A, and Dwivedi R (2023) Global Regions, Biological Diversity, and Urban Land to Significance. _Applied Science and Engineering Journal for Advanced Research_, **2**: 1--7.
* Welch H, Liu OR, Riekkola L, Abrahms B, Hazen EL, and Samhouri JF (2023) Selection of planning unit size in dynamic management strategies to reduce human‐wildlife conflict. _Conservation Biology_, **38**: e14201.

### 2022

* André LV, Van Wynsberge S, Chinain M, Gatti CMI, Liao V, and Andréfouët S (2022) Spatial solutions and their impacts when reshuffling coastal management priorities in small islands with limited diversification opportunities. _Sustainability_, **14**: 3871.
* de Assis Barros L, Venter M, Elkin C, and Venter O (2022) Managing forests for old-growth attributes better promotes the provision of ecosystem services than current age-based old-growth management. _Forest Ecology and Management_, **511**: 120130.
* Benez-Secanho FJ, Dwivedi P, Ferreira S, Hepinstall-Cymerman J, and Wenger S (2022) Trade-offs between the value of ecosystem services and connectivity among protected areas in the Upper Chattahoochee watershed. _Environmental Management_, **69**: 937--951.
* Brito-Morales I, Schoeman DS, Everett JD, Klein CJ, Dunn DC, García Molinos J., Burrows MT, Buenafe KCV, Dominguez RM, Possingham HP, and Richardson AJ (2022) Towards climate-smart, three-dimensional protected areas for biodiversity conservation in the high seas. _Nature Climate Change_, **12**: 402--407.
* Burbano-Girón J, Jantke K, Molina-Berbeo MA, Buriticá-Mejía N, Urbina-Cardona JN, Sánchez-Clavijo LM, and Etter A (2022) An assessment of spatial conservation priorities for biodiversity attributes: Composition, structure, and function of Neotropical biodiversity. _Biological Conservation_, **265**: 109421.
* Chung HI, Choi Y, Yoo Y, Engler R, Lee K, and Jeon SW (2022) Integrated spatial model based evaluation methodology for optimal invasive species management: common ragweed in the Republic of Korea. _Environmental Research Letters_, **17**: 034047.
* Daberger M, Kuemmerle T, Khaleghi Hamidi A, Khalatbari L, Abolghasemi H, Mirzadeh HR, and Ghoddousi A (2022) Prioritizing livestock grazing right buyouts to safeguard Asiatic cheetahs from extinction. _Conservation Science and Practice_, **4**: e12832.
* González-Fernández A, González-Salazar C, Sunny A, Ruíz-Gutiérrez F, and Chávez C (2022) Determination of priority areas for amphibian conservation in Guerrero (Mexico), through systematic conservation planning tools. _Journal for Nature Conservation_, **68**: 126235.
* Hanson JO, Vincent J, Schuster R, Fahrig L, Brennan A, Martin AE, Hughes JS, Pither R, and Bennett JR (2022) A comparison of approaches for including connectivity in systematic conservation planning. _Journal of Applied Ecology_, **59**: 2507--2519.
* Henry RC, Arneth A, Jung M, Rabin SS, Rounsevell MD, Warren F, and Alexander P (2022) Global and regional health and food security under strict conservation scenarios. _Nature Sustainability_, **5**: 303--310.
* Frank F, Volante J, Calamari N, Peri PL, González Chávez B, García Martínez P, Mosciaro MJ, Martín G, Benito Amaro I, Guerrero IP, and Casellas K (2022) A multi-model approach to explore sustainable food and land use pathways for Argentina. _Sustainability Science_, **18**: 347--369.
* Ladouceur E, McGowan J, Huber P, Possingham H, Scridel D, van Klink R, Poschlod P, Cornelissen JHC, Bonomi C, and Jiménez-Alfaro B (2022) An objective-based prioritization approach tosm support trophic complexity through ecological restoration species mixes. _Journal of Applied Ecology_, **59**: 394--407.
* Neo L, Tan HT, and Wong KM (2022) Too little, too late? Conservation exigencies for Borneo inferred from biogeographic considerations of its endemic plant genera against intense landscape modifications. _Biodiversity and Conservation_, **31**: 59--76.
* Paradinas I, Giménez J, Conesa D, López-Quílez A, and Pennino MG (2022) Evidence for spatiotemporal shift in demersal fishery management priority areas in the western Mediterranean. _Canadian Journal of Fisheries and Aquatic Sciences_, **79**: 1641--1654.
* Proctor CA, Schuster R, Buxton RT, and Bennett JR (2022) Prioritization of public and private land to protect species at risk habitat. _Conservation Science and Practice_, **4**: e12771.
* Simkin RD, Seto KC, McDonald RI, and Jetz W (2022) Biodiversity impacts and conservation implications of urban land expansion projected to 2050. _Proceedings of the National Academy of Sciences_, **119**, e2117297119.
* Wilson S, Lin H-Y, Schuster R, González AM, Gómez C, Botero‐Delgadillo E, Bayly NJ, Bennett JR, Rodewald AD, Roehrdanz P, and Ruiz Gutierrez V (2022) Opportunities for the conservation of migratory birds to benefit threatened resident vertebrates in the Neotropics. _Journal of Applied Ecology_, **59**: 653--663.
* de Zwaan DR, Alavi N, Mitchell GW, Lapen DR, Duffe J, and Wilson S (2022) Balancing conservation priorities for grassland and forest specialist bird communities in agriculturally dominated landscapes. _Biological Conservation_, **265**: 109402.

### 2021

* Carroll KA (2021) Systematic prioritization protocol applied to wolverine habitat connectivity. _STAR Protocols_, **2**: 100882.
* Combes M, Vaz S, Grehan A, Morato T, Arnaud-Haond S, Dominguez-Carrió C, Fox A, González-Irusta JM, Johnson D, Callery O, Davies A, Fauconnet L, Kenchington E, Orejas C, Roberts JM, Taranto G, and Menot L (2021) Systematic conservation planning at an ocean basin scale: Identifying a viable network of deep-sea protected areas in the North Atlantic and the Mediterranean. _Frontiers in Marine Science_, **8**: 611358.
* Delso Á, Fajardo J, and Muñoz J (2021) Protected area networks do not represent unseen biodiversity. _Scientific Reports_, **11**: 12275.
* Duchardt CJ, Monroe AP, Heinrichs JA, O'Donnell MS, Edmunds DR, and Aldridge CL (2021) Prioritizing restoration areas to conserve multiple sagebrush-associated wildlife species. _Biological Conservation_, **260**: 109212.
* Carroll KA, Inman RM, Hansen AJ, Lawrence RL, and Barnett K (2021) A framework for collaborative wolverine connectivity conservation. _iScience_, **24**: 102840.
* Jung M, Arnell A, de Lamo X, García-Rangel S, Lewis M, Mark J, Merow C, Miles L, Ondo I, Pironon S, Ravilious C, Rivers M, Schepashenko D, Tallowin O, van Soesbergen A, Govaerts R, Boyle BL, Enquist BJ, Feng X, Gallagher R, Maitner B, Meiri S, Mulligan M, Ofer G, Roll U, Hanson JO, Jetz W, Di Marco M, McGowan J, Rinnan DS, Sachs JD, Lesiv M, Adams VM, Andrew SC, Burger JR, Hannah L, Marquet PA, McCarthy JK, Morueta-Holme N, Newman EA, Park DS, Roehrdanz PR, Svenning J-C, Violle C, Wieringa JJ, Wynne G, Fritz S, Strassburg BBN, Obersteiner M, Kapos V, Burgess N, Schmidt-Traub G, and Visconti P (2021) Areas of global importance for conserving terrestrial biodiversity, carbon and water. _Nature Ecology and Evolution_, **5**: 1499--1509.
* Magris RA, Costa MD, Ferreira CE, Vilar CC, Joyeux JC, Creed JC, Copertino MS, Horta PA, Sumida PYG, Francini-Filho RB, and Floeter SR (2021). A blueprint for securing Brazil's marine biodiversity and supporting the achievement of global conservation goals. _Diversity and Distributions_, **27**: 198-215.
* Southee FM, Edwards BA, Chetkiewicz CLB, and O'Connor CM (2021) Freshwater conservation planning in the far north of Ontario, Canada: identifying priority watersheds for the conservation of fish biodiversity in an intact boreal landscape. _FACETS_, **6**: 90--117.
* von Takach B, Penton CE, Murphy BP, Radford IJ, Davies HF, Hill BM, and Banks SC (2021) Population genomics and conservation management of a declining tropical rodent. _Heredity_, **126**: 763--775.
* Xuereb A, D'Aloia CC, Andrello M, Bernatchez L, and Fortin M-J (2021), Incorporating putatively neutral and adaptive genomic data into marine conservation planning. _Conservation Biology_, **35**: 909--920.
* Zheng C, Wen Z, Liu Y, Guo Q, Jiang Y, Ren H, Fan Y, and Yang Y (2021) Integrating habitat suitability and the near-nature restoration priorities into revegetation plans Based on potential vegetation distribution. _Forests_, **12**: 218.

### 2020

* Bryant BP, Kelsey TR, Vogl AL, Wolny SA, MacEwan DJ, Selmants PC, Biswas T, and Butterfield HS (2020) Shaping land use change and ecosystem restoration in a water-stressed agricultural landscape to achieve multiple benefits. _Frontiers in Sustainable Food Systems_, **4**: 138.
* Flower J, Ramdeen R, Estep A, Thomas LR, Francis S, Goldberg G, Johnson AE, McClintock W, Mendes SR, Mengerink K, and O'Garro M (2020) Marine spatial planning on the Caribbean island of Montserrat: Lessons for data-limited small islands. _Conservation Science and Practice_, **2**: e158.
* Hanson JO, Marques A, Ver&#237;ssimo A, Camacho-Sanchez M, Velo-Ant&#243;n G, Mart&#237;nez-Solano &#205;, and Carvalho SB (2020) Conservation planning for adaptive and neutral evolutionary processes. _Journal of Applied Ecology_, **57**: 2159--2169.
* Hanson JO, Rhodes JR, Butchart SHM, Buchanan GM, Rondinini C, Ficetola GF, and Fuller RA (2020). Global conservation of species' niches. _Nature_, **580**: 232--234.
* Lin H-Y, Robinson KF, and Walter L (2020) Trade-offs among road-stream crossing upgrade prioritizations based on connectivity restoration and erosion risk control. _River Research and Applications_, **36**: 371--382.
* Lin H-Y, Schuster R, Wilson S, Cooke SJ, Rodewald AD, and Bennett JR (2020) Integrating season-specific needs of migratory and resident birds in conservation planning. _Biological Conservation_, **252**, 108826.
* Pinsky ML, Rogers LA, Morley JW, and Fr&#246;licher TL (2020) Ocean planning for species on the move provides substantial benefits and requires few trade-offs. _Science Advances_, **6**: eabb8428.
* Schuster R, Hanson JO, Strimas-Mackey M, and Bennett JR (2020) Exact integer linear programming solvers outperform simulated annealing for solving conservation planning problems. _PeerJ_, **8**: e9258.
* Scriven SA, Williams SH, Ghani MA, Agama AL, Benedick S, Brodie JF, Hamer KC, McClean CJ, Reynolds G, and Hill JK (2020) Assessing the effectiveness of protected areas for conserving range-restricted rain forest butterflies in Sabah, Borneo. _Biotropica_, **52**: 380--391.
* Visalli ME, Best BD, Cabral RB, Cheung WWL, Clark NA, Garilao C, Kaschner K, Kesner-Reyes K, Lam VWY, Maxwell SM, Mayorga J, Moeller HV, Morgan L, Crespo GO, Pinsky ML, White TD, and McCauley DJ (2020) Data-driven approach for highlighting priority areas for protection in marine areas beyond national jurisdiction. _Marine Policy_, **122**: 103927.
* Williams SH, Scriven SA, Burslem DF, Hill JK, Reynolds G, Agama AL, Kugan F, Maycock CR, Khoo E, Hastie AY, Sugau JB (2020) Incorporating connectivity into conservation planning for optimal representation of multiple species and ecosystem services. _Conservation Biology_, **34**: 934--942.

### 2019

* Bombi P, Gnetti V, D'Andrea E, De Cinti B, Taglianti AV, Bologna MA, and Matteucci G (2019) Identifying priority sites for insect conservation in forest ecosystems at high resolution: the potential of LiDAR data. _Journal of Insect Conservation_, **23**: 689--698.
* Domisch S, Friedrichs M, Hein T, Borgwardt F, Wetzig A, J&auml;hnig SC, and Langhans SD (2019) Spatially explicit species distribution models: A missed opportunity in conservation planning? _Diversity and Distributions_, **25**: 758--769.
* Hanson JO, Fuller RA, and Rhodes JR (2019) Conventional methods for enhancing connectivity in conservation planning do not always maintain gene flow. _Journal of Applied Ecology_, **56**: 913--922.
* Rodewald AD, Strimas-Mackey M, Schuster R, and Arcese P (2019) Beyond canaries in coal mines: Co-occurrence of Andean mining concessions and migratory birds. _Perspectives in Ecology and Conservation_, **17**: 151--156.
* Rodewald AD, Strimas-Mackey M, Schuster R, and Arcese P (2019) Tradeoffs in the value of biodiversity feature and cost data in conservation prioritization. _Scientific Reports_, **9**: 15921.
* Schuster R, Wilson S, Rodewald A, Arcese P, Fink D, Auer T, and Bennett J (2019) Optimizing the conservation of migratory species over their full annual cycle. _Nature Communications_, **10**: 1754.
* Tack JD, Jakes AF, Jones PF, Smith JT, Newton RE, Martin BH, Hebblewhite M, and Naugle DE (2019) Beyond protected areas: Private lands and public policy anchor intact pathways for multi-species wildlife migration. _Biological Conservation_, **234**: 18--27.

### 2017

* Rosauer DF, Pollock LJ, Linke S, and Jetz W (2017) Phylogenetically informed spatial planning is required to conserve the mammalian tree of life. _Proceedings of the Royal Society of London B: Biological Sciences_, **284**: 20170627.

## Review articles

### 2025

* Giakoumi S, Richardson AJ, Doxa A, Moro S, Andrello M, Hanson JO, Hermoso V, Mazor T, McGowan J, Kujala H, Law E, Álvarez Romero JG, Magris RA, Gissi E, Arafeh-Dalmau N, Metaxas A, Virtanen EA, Ban NC, Runya RM, Dunn DC, Fraschetti S, Galparsoro I, Smith RJ, Bastardie F, Stelzenmüller V, Possingham HP, and Katsanevakis S (2025) Advances in systematic conservation planning to meet global biodiversity goals. _Trends in Ecology and Evolution_, **In press**: DOI&#58;10.1016/j.tree.2024.12.002.

### 2024

* Frazier AE and Song L (2024) Artificial Intelligence in Landscape Ecology: Recent Advances, Perspectives, and Opportunities. *Current Landscape Ecology Reports*, **10**: 1.

### 2023

* Burns ES, Lopazanski C, Flower J, Thomas LR, Bradley D, and Lester SE (2023) Finding harmony in Marine Protected Area design guidelines. _Conservation Science and Practice_, **5**: e12946.
* Piczak ML, Robichaud JA, Morrison P, Rous AM, Mulder IM, Hill CJ, Prystay TS, Rosner-Katz H, Robinson KF, Bennett JR, and Cooke SJ (2023) Structured decision making remains underused in ecological restoration despite opportunities. _Environment Systems and Decisions_, **44**: 1--15.

### 2022

* Magdalena UR, Gonçalves de Souza GB, and Amorim RR (2022) Spatial analysis guiding decision making in environmental conservation: Systematic conservation planning and ecosystem services. _Progress in Physical Geography: Earth and Environment_, **47**: 123--139.

### 2021

* Queffelec B, Bonnin M, Ferreira B, Bertrand S, Teles Da Silva S, Diouf F,  Trouillet B, Cudennec A, Brunel A, Billant O, and Toonen H (2021) Marine spatial planning and the risk of ocean grabbing in the tropical Atlantic. _ICES Journal of Marine Science_, **78**: 1196--1208.

### 2020

* Pollock LJ, O'Connor LM, Mokany K, Rosauer DF, Talluto MV, and Thuiller W (2020) Protecting Biodiversity (in all its complexity): New models and methods. _Trends in Ecology & Evolution_, **35**: 1119--1128.
* Velazco SJE, Ribeiro BR, Laureto LMO, and J&uacute;nior PDM (2020) Overprediction of species distribution models in conservation planning: A still neglected issue with strong effects. _Biological Conservation_, **252**, 108822.

### 2019

* Balbar AC and Metaxas A (2019) The current application of ecological connectivity in the design of marine protected areas. _Global Ecology and Conservation_, **17**: e00569.

## Book chapters

* Riginos C and Beger M (2022). Incorporating Genetic Measures of Connectivity and Adaptation in Marine Spatial Planning for Corals in _Coral Reef Conservation and Restoration in the Omics Age_ (eds van Oppen MJH and Aranda Lastra M). Coral Reefs of the World. Springer, Cham.
* Kuemmerle T, Kastner T, Meyfroidt P, and Qin S (2019) Conservation Telecouplings in _Telecoupling: Exploring Land-Use Change in a Globalised World, Springer International Publishing_ (eds Friis C and Nielsen J). Palgrave Studies in Natural Resource Management. Palgrave Macmillan, Cham.
