---
title: "Publication Record"
output:
  rmarkdown::html_vignette:
    toc: true
    fig_caption: true
    self_contained: yes
fontsize: 11pt
documentclass: article
vignette: >
  %\VignetteIndexEntry{Publication Record}
  %\VignetteEngine{knitr::rmarkdown_notangle}
---

This vignette contains a list of publications that have cited the _prioritizr R_ package. We would love to hear from you if you have used _prioritizr R_ package in your own work. Please [file an issue on GitHub](https://github.com/prioritizr/prioritizr/issues/new) so we can add your work to this list.

## Research articles

### 2020
* [Flower J, Ramdeen R, Estep A, Thomas LR, Francis S, Goldberg G, Johnson AE, McClintock W, Mendes SR, Mengerink K, and O'Garro M (2020) Marine spatial planning on the Caribbean island of Montserrat: Lessons for data-limited small islands. _Conservation Science and Practice_, **2**: e158.](https://doi.org/10.1111/csp2.158)
* [Hanson JO, Marques A, Ver&#237;ssimo A, Camacho-Sanchez M, Velo-Ant&#243;n G, Mart&#237;nez-Solano &#205;, and Carvalho SB (2020) Conservation planning for adaptive and neutral evolutionary processes. _Journal of Applied Ecology_, **In press**: https://doi.org/10.1111/1365-2664.13718.](https://doi.org/10.1111/1365-2664.13718)
* [Hanson JO, Rhodes JR, Butchart SHM, Buchanan GM, Rondinini C, Ficetola GF, and Fuller RA (2020). Global conservation of species' niches. _Nature_, **580**: 232--234.](https://doi.org/10.1038/s41586-020-2138-7)
* [Lin H-Y, Robinson KF, and Walter L (2020) Trade-offs among road-stream crossing upgrade prioritizations based on connectivity restoration and erosion risk control. _River Research and Applications_, **36**: 371--382.](https://doi.org/10.1002/rra.3593)
* [Schuster R, Hanson JO, Strimas-Mackey M, and Bennett JR (2020) Exact integer linear programming solvers outperform simulated annealing for solving conservation planning problems. _PeerJ_, **8**: e9258.](https://doi.org/10.7717/peerj.9258)
* [Scriven SA, Williams SH, Ghani MA, Agama AL, Benedick S, Brodie JF, Hamer KC, McClean CJ, Reynolds G, and Hill JK (2020) Assessing the effectiveness of protected areas for conserving range-restricted rain forest butterflies in Sabah, Borneo. _Biotropica_, **52**: 380--391.](https://doi.org/10.1111/btp.12708)
* [Visalli ME, Best BD, Cabral RB, Cheung WWL, Clark NA, Garilao C, Kaschner K, Kesner-Reyes K, Lam VWY, Maxwell SM, Mayorga J, Moeller HV, Morgan L, Crespo GO, Pinsky ML, White TD, and McCauley DJ (2020) Data-driven approach for highlighting priority areas for protection in marine areas beyond national jurisdiction. _Marine Policy_, **In press**: https://doi.org/10.1016/j.marpol.2020.103927.](https://doi.org/10.1016/j.marpol.2020.103927)
* [Williams SH, Scriven SA, Burslem DF, Hill JK, Reynolds G, Agama AL, Kugan F, Maycock CR, Khoo E, Hastie AY, Sugau JB (2020) Incorporating connectivity into conservation planning for optimal representation of multiple species and ecosystem services. _Conservation Biology_, **34**: 934--942.](https://doi.org/10.1111/cobi.13450)
* [Xuereb A, D'Aloia CC, Andrello M, Bernatchez L, and Fortin M-J (2020), Incorporating putatively neutral and adaptive genomic data into marine conservation planning. _Conservation Biology_, **In press**: https://doi.org/10.1111/cobi.13609.](https://doi.org/10.1111/cobi.13609)

### 2019
* [Bombi P, Gnetti V, D'Andrea E, De Cinti B, Taglianti AV, Bologna MA, and Matteucci G (2019) Identifying priority sites for insect conservation in forest ecosystems at high resolution: the potential of LiDAR data. _Journal of Insect Conservation_, **23**: 689--698.](https://doi.org/10.1007/s10841-019-00162-w)
* [Domisch S, Friedrichs M, Hein T, Borgwardt F, Wetzig A, J&auml;hnig SC, and Langhans SD (2019) Spatially explicit species distribution models: A missed opportunity in conservation planning? _Diversity and Distributions_, **25**: 758--769.](https://doi.org/10.1111/ddi.12891)
* [Hanson JO, Fuller RA, and Rhodes JR (2019) Conventional methods for enhancing connectivity in conservation planning do not always maintain gene flow. _Journal of Applied Ecology_, **56**: 913--922.](https://doi.org/10.1111/1365-2664.13315)
* [Rodewald AD, Strimas-Mackey M, Schuster R, and Arcese P (2019) Beyond canaries in coal mines: Co-occurrence of Andean mining concessions and migratory birds. _Perspectives in Ecology and Conservation_, **17**: 151--156.](https://doi.org/10.1016/j.pecon.2019.08.002)
* [Rodewald AD, Strimas-Mackey M, Schuster R, and Arcese P (2019) Tradeoffs in the value of biodiversity feature and cost data in conservation prioritization. _Scientific Reports_ **9**: 15921.](https://doi.org/10.1038/s41598-019-52241-2)
* [Schuster R, Wilson S, Rodewald A, Arcese P, Fink D, Auer T, and Bennett J (2019) Optimizing the conservation of migratory species over their full annual cycle. _Nature Communications_, **10**: 1754.](https://doi.org/10.1038/s41467-019-09723-8)
* [Tack JD, Jakes AF, Jones PF, Smith JT, Newton RE, Martin BH, Hebblewhite M, and Naugle DE (2019) Beyond protected areas: Private lands and public policy anchor intact pathways for multi-species wildlife migration. _Biological Conservation_, **234**: 18--27.](https://doi.org/10.1016/j.biocon.2019.03.017)

### 2017
* [Rosauer DF, Pollock LJ, Linke S, and Jetz W (2017) Phylogenetically informed spatial planning is required to conserve the mammalian tree of life. _Proceedings of the Royal Society of London B: Biological Sciences_, **284**: 20170627.](https://dx.doi.org/10.1098/rspb.2017.0627)


## Review articles

* [Balbar AC, and Metaxas A (2019) The current application of ecological connectivity in the design of marine protected areas. _Global Ecology and Conservation_, **17**: e00569.](https://doi.org/10.1016/j.gecco.2019.e00569)

## Book chapters

* [Kuemmerle T, Kastner T, Meyfroidt P, and Qin S (2019) Conservation Telecouplings in _Telecoupling: Exploring Land-Use Change in a Globalised World, Springer International Publishing_ (eds Friis C, and Nielsen J). Palgrave Studies in Natural Resource Management. Palgrave Macmillan, Cham.](https://doi.org/10.1007/978-3-030-11105-2_15)
