<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="description" content="prioritizr"><title>Calibrating trade-offs tutorial • prioritizr</title><!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png"><link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png"><link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png"><link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png"><link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png"><link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png"><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous"><!-- bootstrap-toc --><script src="https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@v1.0.1/dist/bootstrap-toc.min.js" integrity="sha256-4veVQbu7//Lk5TSmc7YV48MxtMy98e26cf5MrgZYnwo=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- search --><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- pkgdown --><script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet"><meta property="og:title" content="Calibrating trade-offs tutorial"><meta property="og:description" content="prioritizr"><meta property="og:image" content="https://prioritizr.net/logo.png"><!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-70466840-4"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-70466840-4');
</script></head><body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>
    

    <nav class="navbar fixed-top navbar-dark navbar-expand-lg bg-primary"><div class="container">
    
    <a class="navbar-brand me-2" href="../index.html">prioritizr</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">8.0.3.6</small>

    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="nav-item">
  <a class="nav-link" href="../articles/prioritizr.html">Get started</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="../reference/index.html">Reference</a>
</li>
<li class="nav-item dropdown">
  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" id="dropdown-articles">Articles</a>
  <div class="dropdown-menu" aria-labelledby="dropdown-articles">
    <a class="dropdown-item" href="../articles/package_overview.html">Package overview</a>
    <a class="dropdown-item" href="../articles/gurobi_installation_guide.html">Gurobi installation guide</a>
    <a class="dropdown-item" href="../articles/solver_benchmarks.html">Solver benchmarks</a>
    <a class="dropdown-item" href="../articles/publication_record.html">Publication record</a>
  </div>
</li>
<li class="active nav-item dropdown">
  <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" id="dropdown-tutorials">Tutorials</a>
  <div class="dropdown-menu" aria-labelledby="dropdown-tutorials">
    <a class="dropdown-item" href="../articles/connectivity_tutorial.html">Connectivity</a>
    <a class="dropdown-item" href="../articles/calibrating_trade-offs_tutorial.html">Calibrating trade-offs</a>
    <a class="dropdown-item" href="../articles/management_zones_tutorial.html">Management zones</a>
  </div>
</li>
<li class="nav-item">
  <a class="nav-link" href="../news/index.html">Changelog</a>
</li>
      </ul><form class="form-inline my-2 my-lg-0" role="search">
        <input type="search" class="form-control me-sm-2" aria-label="Toggle navigation" name="search-input" data-search-index="../search.json" id="search-input" placeholder="Search for" autocomplete="off"></form>

      <ul class="navbar-nav"><li class="nav-item">
  <a class="external-link nav-link" href="https://github.com/prioritizr/prioritizr/" aria-label="github">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul></div>

    
  </div>
</nav><div class="container template-article">




<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Calibrating trade-offs tutorial</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/prioritizr/prioritizr/blob/HEAD/vignettes/calibrating_trade-offs_tutorial.Rmd" class="external-link"><code>vignettes/calibrating_trade-offs_tutorial.Rmd</code></a></small>
      <div class="d-none name"><code>calibrating_trade-offs_tutorial.Rmd</code></div>
    </div>

    
    
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>Systematic conservation planning requires making trade-offs <span class="citation">(Margules &amp; Pressey 2000; Vane-Wright <em>et al.</em> 1991)</span>. Since different criteria may conflict with one another – or not align perfectly – prioritizations need to make trade-offs between different criteria <span class="citation">(Klein <em>et al.</em> 2013)</span>. Although some criteria can easily be accounted for by using locked constraints or representation targets <span class="citation">(e.g., Dorji <em>et al.</em> 2020; Hermoso <em>et al.</em> 2018)</span>, this is not always the case <span class="citation">(e.g., Beger <em>et al.</em> 2010)</span>. For example, prioritizations often need to balance overall cost with the overall level spatial fragmentation among reserves <span class="citation">(Hermoso <em>et al.</em> 2011; Stewart &amp; Possingham 2005)</span>. Additionally, prioritizations often need to balance the overall level of connectivity among reserves against other criteria <span class="citation">(Hermoso <em>et al.</em> 2012)</span>. Since the best trade-off depends on a range of factors – such as available budgets, species’ connectivity requirements, and management capacity – finding the best balance can be challenging.</p>
<p>The <em>prioritizr R</em> package provides multi-objective optimization methods to help identify the best trade-offs between different criteria. To achieve this, a conservation planning problem can be formulated with a primary objective (e.g., <code>add_min_set_objective()</code>) and penalties (e.g., <code>add_boundary_penalties()</code>) that relate to such criteria. When building the problem, the nature of the trade-offs can be specified using certain parameters (e.g., the <code>penalty</code> parameter of the <code>add_boundary_penalties()</code> function). To identify a prioritization that finds the best balance between different criteria, the trade-off parameters can be tuned using a calibration analysis. These analyses – in the context of systematic conservation planning – typically involve generating a set of candidate prioritizations based on different parameters, measuring their performance according to each of the criteria, and then selecting a prioritization (or set of prioritizations) based on how well they achieve the criteria <span class="citation">(Hermoso <em>et al.</em> 2011; Stewart &amp; Possingham 2005; Hermoso <em>et al.</em> 2012)</span>. For example, the <em>Marxan</em> decision support tool has a range of parameters (e.g., species penalty factors, boundary length modifier) that are calibrated to balance cost, species’ representation, and spatial fragmentation <span class="citation">(Ardron <em>et al.</em> 2010)</span>.</p>
<p>The aim of this tutorial is to provide guidance on calibrating trade-offs when using the <em>prioritizr R</em> package. Here we will explore a couple of different approaches for generating candidate prioritizations, and methods for finding the best balance between different criteria. Specifically, we will try to generate prioritizations that strike the best balance between total cost and spatial fragmentation (measured as total boundary length). As such, the code used in this vignette will be directly applicable when performing a boundary length calibration analysis.</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>Let’s load the packages and dataset used in this tutorial. Since this tutorial uses the <em>prioritizrdata R</em> package along with several other <em>R</em> packages (see below), please ensure that they are all installed. This particular dataset comprises two objects: <code>tas_pu</code> and <code>tas_features</code>. Although we will briefly describe this dataset below, please refer <code>?prioritizrdata::tas_data</code> for further details.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(prioritizrdata)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(prioritizr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(topsis)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(withr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># set seed for reproducibility</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">500</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># load planning unit data</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>tas_pu <span class="ot">&lt;-</span> <span class="fu">get_tas_pu</span>()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tas_pu)</span></code></pre></div>
<pre><code>## Simple feature collection with 1130 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 298809.6 ymin: 5167775 xmax: 613818.8 ymax: 5502544
## Projected CRS: WGS 84 / UTM zone 55S
## [38;5;246m# A tibble: 1,130 × 5[39m
##       id  cost locked_in locked_out                                         geom
##    [3m[38;5;246m&lt;int&gt;[39m[23m [3m[38;5;246m&lt;dbl&gt;[39m[23m [3m[38;5;246m&lt;lgl&gt;[39m[23m     [3m[38;5;246m&lt;lgl&gt;[39m[23m                                [3m[38;5;246m&lt;MULTIPOLYGON [m]&gt;[39m[23m
## [38;5;250m 1[39m     1 60.2  FALSE     TRUE       (((328497 5497704, 326783.8 5500050, 326775…
## [38;5;250m 2[39m     2 19.9  FALSE     FALSE      (((307121.6 5490487, 305344.4 5492917, 3053…
## [38;5;250m 3[39m     3 59.7  FALSE     TRUE       (((321726.1 5492382, 320111 5494593, 320127…
## [38;5;250m 4[39m     4 32.4  FALSE     FALSE      (((304314.5 5494324, 304342.2 5494287, 3043…
## [38;5;250m 5[39m     5 26.2  FALSE     FALSE      (((314958.5 5487057, 312336 5490646, 312339…
## [38;5;250m 6[39m     6 51.3  FALSE     FALSE      (((327904.3 5491218, 326594.6 5493012, 3284…
## [38;5;250m 7[39m     7 32.3  FALSE     FALSE      (((308194.1 5481729, 306601.2 5483908, 3066…
## [38;5;250m 8[39m     8 38.4  FALSE     FALSE      (((322792.7 5483624, 319965.3 5487497, 3199…
## [38;5;250m 9[39m     9  3.55 FALSE     FALSE      (((334896.6 5490731, 335610.4 5492490, 3357…
## [38;5;250m10[39m    10  1.83 FALSE     FALSE      (((356377.1 5487952, 353903.1 5487635, 3538…
## [38;5;246m# ℹ 1,120 more rows[39m</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load feature data</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>tas_features <span class="ot">&lt;-</span> <span class="fu">get_tas_features</span>()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tas_features)</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 398, 359, 33  (nrow, ncol, nlyr)
## resolution  : 1000, 1000  (x, y)
## extent      : 288801.7, 647801.7, 5142976, 5540976  (xmin, xmax, ymin, ymax)
## coord. ref. : WGS 84 / UTM zone 55S (EPSG:32755) 
## source      : tas_features.tif 
## names       : Banks~lands, Bould~marks, Calli~lands, Cool ~orest, Eucal~hyll), Eucal~torey, ... 
## min values  :           0,           0,           0,           0,           0,           0, ... 
## max values  :           1,           1,           1,           1,           1,           1, ...</code></pre>
<p>The <code>tas_pu</code> object contains planning units represented as spatial polygons (i.e., converted to a <code>sf::st_sf()</code> object). This object has three columns that denote the following information for each planning unit: a unique identifier (<code>id</code>), unimproved land value (<code>cost</code>), and current conservation status (<code>locked_in</code>). Specifically, the conservation status column indicates if at least half the area planning unit is covered by existing protected areas (denoted by a value of 1) or not (denoted by a value of zero).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot map of planning unit costs</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tas_pu[, <span class="st">&quot;cost&quot;</span>])</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-5-1.png" width="336" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot map of planning unit statuses</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tas_pu[, <span class="st">&quot;locked_in&quot;</span>])</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-5-2.png" width="336" style="display: block; margin: auto;" /></p>
<p>The <code>tas_features</code> object describes the spatial distribution of different vegetation communities (using presence/absence data). We will use the vegetation communities as the biodiversity features for the prioritization.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot map of the first four vegetation classes</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tas_features[[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]])</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-6-1.png" width="432" style="display: block; margin: auto;" /></p>
<p>We can use this dataset to generate a prioritization. Specifically, we will use the minimum set objective so that the optimization process minimizes total cost. We will add representation targets to ensure that prioritizations cover 17% of each vegetation community. Additionally, we will add constraints to ensure that planning units covered by existing protected areas are selected (i.e., locked in). Finally, we will specify that the conservation planning exercise involves binary decisions (i.e., selecting or not selecting planning units for protected area establishment).</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a problem</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>()</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># print problem</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p0)</span></code></pre></div>
<pre><code>## A conservation problem ([34m&lt;ConservationProblem&gt;[39m)
## [36m├•data[39m
## [36m│├•[39mfeatures:    [34m&quot;Banksia woodlands&quot;[39m , … (33 total)
## [36m│└•[39mplanning units:
## [36m│[39m [36m├•[39mdata:       [34m&lt;sftbl_dftbldata.frame&gt;[39m (1130 total)
## [36m│[39m [36m├•[39mcosts:      continuous values (between [34m0.1925[39m and [34m61.9273[39m)
## [36m│[39m [36m├•[39mextent:     [34m298809.5764[39m, [34m5167774.5993[39m, [34m613818.7743[39m, [34m5502543.7119[39m (xmin, ymin, xmax, ymax)
## [36m│[39m [36m└•[39mCRS:        WGS 84 / UTM zone 55S (projected)
## [36m├•formulation[39m
## [36m│├•[39mobjective:   minimum set objective
## [36m│├•[39mpenalties:   [38;5;249mnone specified[39m
## [36m│├•[39mtargets:     relative targets (between [34m0.17[39m and [34m0.17[39m)
## [36m│├•[39mconstraints:
## [36m││└•[39m1:          locked in constraints (257 planning units)
## [36m│└•[39mdecisions:   binary decision
## [36m└•optimization[39m
##  [36m├•[39mportfolio:   shuffle portfolio (`number_solutions` = [34m1[39m, …)
##  [36m└•[39msolver:      gurobi solver (`gap` = [34m0.1[39m, `time_limit` = [34m2147483647[39m, `first_feasible` = [34mFALSE[39m, …)
## [90m# ℹ Use `summary(...)` to see complete formulation.[39m</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># solve problem</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>s0 <span class="ot">&lt;-</span> <span class="fu">solve</span>(p0)</span></code></pre></div>
<pre><code>## Set parameter Username
## Set parameter TimeLimit to value 2147483647
## Set parameter MIPGap to value 0.1
## Set parameter Presolve to value 2
## Set parameter Threads to value 1
## Academic license - for non-commercial use only - expires 2025-04-21
## Gurobi Optimizer version 11.0.1 build v11.0.1rc0 (linux64 - &quot;Ubuntu 22.04.4 LTS&quot;)
## 
## CPU model: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
## Thread count: 4 physical cores, 8 logical processors, using up to 1 threads
## 
## Optimize a model with 33 rows, 1130 columns and 8157 nonzeros
## Model fingerprint: 0x09e16ac8
## Variable types: 0 continuous, 1130 integer (1130 binary)
## Coefficient statistics:
##   Matrix range     [2e-06, 6e+01]
##   Objective range  [2e-01, 6e+01]
##   Bounds range     [1e+00, 1e+00]
##   RHS range        [2e-01, 2e+03]
## Found heuristic solution: objective 10059.047375
## Presolve removed 19 rows and 354 columns
## Presolve time: 0.00s
## Presolved: 14 rows, 776 columns, 2296 nonzeros
## Variable types: 0 continuous, 776 integer (776 binary)
## Found heuristic solution: objective 9107.7729975
## 
## Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.01 work units)
## Thread count was 1 (of 8 available processors)
## 
## Solution count 2: 9107.77 10059 
## 
## Optimal solution found (tolerance 1.00e-01)
## Best objective 9.107772997535e+03, best bound 8.496084047117e+03, gap 6.7161%</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print result</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(s0)</span></code></pre></div>
<pre><code>## Simple feature collection with 1130 features and 5 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 298809.6 ymin: 5167775 xmax: 613818.8 ymax: 5502544
## Projected CRS: WGS 84 / UTM zone 55S
## [38;5;246m# A tibble: 1,130 × 6[39m
##       id  cost locked_in locked_out solution_1                              geom
##    [3m[38;5;246m&lt;int&gt;[39m[23m [3m[38;5;246m&lt;dbl&gt;[39m[23m [3m[38;5;246m&lt;lgl&gt;[39m[23m     [3m[38;5;246m&lt;lgl&gt;[39m[23m           [3m[38;5;246m&lt;dbl&gt;[39m[23m                [3m[38;5;246m&lt;MULTIPOLYGON [m]&gt;[39m[23m
## [38;5;250m 1[39m     1 60.2  FALSE     TRUE                0 (((328497 5497704, 326783.8 5500…
## [38;5;250m 2[39m     2 19.9  FALSE     FALSE               0 (((307121.6 5490487, 305344.4 54…
## [38;5;250m 3[39m     3 59.7  FALSE     TRUE                0 (((321726.1 5492382, 320111 5494…
## [38;5;250m 4[39m     4 32.4  FALSE     FALSE               0 (((304314.5 5494324, 304342.2 54…
## [38;5;250m 5[39m     5 26.2  FALSE     FALSE               0 (((314958.5 5487057, 312336 5490…
## [38;5;250m 6[39m     6 51.3  FALSE     FALSE               0 (((327904.3 5491218, 326594.6 54…
## [38;5;250m 7[39m     7 32.3  FALSE     FALSE               0 (((308194.1 5481729, 306601.2 54…
## [38;5;250m 8[39m     8 38.4  FALSE     FALSE               0 (((322792.7 5483624, 319965.3 54…
## [38;5;250m 9[39m     9  3.55 FALSE     FALSE               0 (((334896.6 5490731, 335610.4 54…
## [38;5;250m10[39m    10  1.83 FALSE     FALSE               0 (((356377.1 5487952, 353903.1 54…
## [38;5;246m# ℹ 1,120 more rows[39m</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create column for making a map of the prioritization</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>s0<span class="sc">$</span>map_1 <span class="ot">&lt;-</span> <span class="fu">case_when</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  s0<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;locked in&quot;</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  s0<span class="sc">$</span>solution_1 <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;priority&quot;</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;other&quot;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot map of prioritization</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  s0[, <span class="st">&quot;map_1&quot;</span>], <span class="at">pal =</span> <span class="fu">c</span>(<span class="st">&quot;purple&quot;</span>, <span class="st">&quot;grey90&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="cn">NULL</span>, <span class="at">key.pos =</span> <span class="dv">1</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-8-1.png" width="336" style="display: block; margin: auto;" /></p>
<p>We can see that the priority areas identified by the prioritization are scattered across the study area (shown in green). Indeed, none of the priority areas are connected to existing protected areas (shown in purple), and very of them are connected with other priority areas. As such, the prioritization has a high level of spatial fragmentation. If it is important to avoid such levels of spatial fragmentation, then we will need to explicitly account for spatial fragmentation in the optimization process.</p>
</div>
<div id="preliminary-processing" class="section level2">
<h2>Preliminary processing</h2>
<p>We need to conduct some preliminary processing procedures to prepare the data for subsequent analysis. This is important to help make it easier to find suitable trade-off parameters, and avoid numerical scaling issues that can result in overly long run times (see <code>presolve_check()</code> for further information). These processing steps are akin to data scaling (or normalization) procedures that are applied in statistical analysis to improve model convergence.</p>
<p>The first processing procedure involves setting the cost values for all locked in planning units to zero. This is so that the total cost estimates of the prioritization reflects the total cost of establishing new protected areas – not just total land value. In other words, we want the total cost estimate for a prioritization to reflect the cost of implementing conservation actions. <strong>This procedure is especially important when using the hierarchical approach described below, so that cost thresholds are based on percentage increases in the cost of establishing new protected areas.</strong></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set costs for planning units covered by existing protected areas to zero</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>tas_pu<span class="sc">$</span>cost[tas_pu<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plot map of planning unit costs</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tas_pu[, <span class="st">&quot;cost&quot;</span>])</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-9-1.png" width="336" style="display: block; margin: auto;" /></p>
<p>The second procedure involves pre-computing the boundary length data and manually re-scaling the boundary length values. This procedure is important because boundary length values are often very high, which can cause numerical issues that result in excessive run times (see <code>presolve_check()</code> for further details).</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate boundary length data for the planning units</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tas_bd <span class="ot">&lt;-</span> <span class="fu">boundary_matrix</span>(tas_pu)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># manually re-scale the boundary length values</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>tas_bd <span class="ot">&lt;-</span> <span class="fu">rescale_matrix</span>(tas_bd)</span></code></pre></div>
<p>After applying these procedures, our data is ready for subsequent analysis.</p>
</div>
<div id="generating-candidate-prioritizations" class="section level2">
<h2>Generating candidate prioritizations</h2>
<p>Here we will start the calibration analysis by generating a set of candidate prioritizations. Specifically, these prioritizations will be generated using different parameters to specify different trade-offs between the different criteria. Since this tutorial involves navigating trade-offs between the overall cost of a prioritization and the level of spatial fragmentation associated with a prioritization (as measured by total boundary length), we will generate prioritizations using different parameters related to these criteria. We will examine two approaches for generating candidate prioritizations based on multi-objective optimization procedures. <strong>Although we’ll be examining both approaches in this tutorial, you would normally only use one of these approaches when conducting your own analysis</strong></p>
<div id="blended-approach" class="section level3">
<h3>Blended approach</h3>
<p>The blended approach for multi-objective optimization involves combining separate criteria (e.g., total cost and total boundary length) into a single joint criterion. To achieve this, a trade-off (or scaling) parameter is used to specify the relative importance of each criterion. This approach is the default approach provided by the <em>prioritizr R</em> package. Specifically, each of the functions for adding a penalty to a problem formulation (e.g., <code>add_boundary_penalties()</code>) contains a parameter to control the relative importance of the penalties (i.e., the <code>penalty</code> parameter). For example, when using the <code>add_boundary_penalties()</code> function, setting a high <code>penalty</code> value will indicate that it is important to reduce the overall exposed boundary (perimeter) of the prioritization.</p>
<p>The main challenge with the blended approach is identifying a range of suitable <code>penalty</code> values to generate candidate prioritizations. If we set a <code>penalty</code> value that is too low, then the penalties will have no effect (e.g., boundary length penalties would have no effect on the prioritization). If we set a <code>penalty</code> value too high, then the prioritization will effectively ignore the primary objective. In such cases, the prioritization will be overly spatially clustered – because the planning unit cost values have no effect — and contain a single reserve. Thus we need to find a suitable range of <code>penalty</code> values before we can generate a set of candidate prioritizations.</p>
<p>We can find a suitable range of <code>penalty</code> values by generating a set of preliminary prioritizations. These preliminary prioritizations will be based on different <code>penalty</code> values – similar to the process for generating the candidate prioritizations – but solved using customized settings that sacrifice optimality for fast run times (see below for details). This is especially important because specifying a <code>penalty</code> value that is too high will cause the optimization process to take a very long time to generate a solutions (due to the numerical scaling issues mentioned previously). To find a suitable range of <code>penalty</code> values, we need to identify an upper limit for the <code>penalty</code> value (i.e., the highest <code>penalty</code> value that result in a prioritization containing a single reserve). Let’s create some preliminary <code>penalty</code> to identify this upper limit. <strong>Please note that you might need to adjust the <code>prelim_upper</code> value to find the upper limit when analyzing different datasets.</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a range of different penalty values</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="do">## note that we use a power scale to avoid focusing on very high penalty values</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>prelim_lower <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">5</span>  <span class="co"># change this for your own data</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>prelim_upper <span class="ot">&lt;-</span> <span class="fl">1.75</span> <span class="co"># change this for your own data</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>prelim_penalty <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(prelim_lower, prelim_upper, <span class="at">length.out =</span> <span class="dv">9</span>), <span class="dv">5</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print penalty values</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prelim_penalty)</span></code></pre></div>
<pre><code>## [1]  0.00001  0.00007  0.00049  0.00340  0.02371  0.16548  1.15478  8.05842
## [9] 56.23413</code></pre>
<p>Next, let’s use the preliminary <code>penalty</code> values to generate preliminary prioritizations. As mentioned earlier, we will generate these preliminary prioritizations using customized settings to reduce runtime. Specifically, we will set a time limit of 10 minutes per run, and relax the optimality gap to 20%. Although we would not normally use such settings – because the resulting prioritizations are not guaranteed to be near-optimal (the default gap is 10%) – this is fine because our goal here is to tune the preliminary <code>penalty</code> values. Indeed, none of these preliminary prioritizations will be considered as candidate prioritizations. <strong>Please note that you might need to set a higher time limit, or relax the optimality gap even further (e.g., 40%) when analyzing larger datasets.</strong></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a problem without boundary penalties</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>()</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># generate preliminary prioritizations based on each penalty</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="do">## note that we specify a relaxed gap and time limit for the solver</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>prelim_blended_results <span class="ot">&lt;-</span> <span class="fu">lapply</span>(prelim_penalty, <span class="cf">function</span>(x) {</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    p0 <span class="sc">%&gt;%</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_boundary_penalties</span>(<span class="at">penalty =</span> x, <span class="at">data =</span> tas_bd) <span class="sc">%&gt;%</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_default_solver</span>(<span class="at">gap =</span> <span class="fl">0.2</span>, <span class="at">time_limit =</span> <span class="dv">10</span> <span class="sc">*</span> <span class="dv">60</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">solve</span>()</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">s =</span> s<span class="sc">$</span>solution_1)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(s) <span class="ot">&lt;-</span> <span class="fu">with_options</span>(<span class="fu">list</span>(<span class="at">scipen =</span> <span class="dv">30</span>), <span class="fu">paste0</span>(<span class="st">&quot;penalty_&quot;</span>, x))</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  s</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="co"># format results as a single spatial object</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>prelim_blended_results <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  tas_pu, <span class="fu">do.call</span>(bind_cols, prelim_blended_results)</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a><span class="co"># preview results</span></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prelim_blended_results)</span></code></pre></div>
<p>After generating the preliminary prioritizations, let’s create some maps to visualize them. In particular, we want to understand how different penalty values influence the spatial fragmentation of the prioritizations.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot maps of prioritizations</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    prelim_blended_results <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;penalty_&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(is.numeric, <span class="cf">function</span>(x) {</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>        prelim_blended_results<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;locked in&quot;</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>        x <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;priority&quot;</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;other&quot;</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    }),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">pal =</span> <span class="fu">c</span>(<span class="st">&quot;purple&quot;</span>, <span class="st">&quot;grey90&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We can see that as the <code>penalty</code> value used to generate the prioritizations increases, the spatial fragmentation of the prioritizations decreases. In particular, we can see that a <code>penalty</code> value of 56.23413 results in a single reserve – meaning this is our best guess of the upper limit. Using this <code>penalty</code> value as an upper limit, we will now generate a second series of prioritizations that will be the candidate prioritizations. Critically, these candidate prioritizations will not be generated using with time limit and be generated using a more suitable gap (i.e., default gap of 10%).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a new set of penalty values</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>penalty <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="fu">log10</span>(prelim_penalty[<span class="dv">9</span>]), <span class="at">length.out =</span> <span class="dv">9</span>), <span class="dv">5</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># generate prioritizations based on each penalty</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>blended_results <span class="ot">&lt;-</span> <span class="fu">lapply</span>(penalty, <span class="cf">function</span>(x) {</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## generate solution</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    p0 <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_boundary_penalties</span>(<span class="at">penalty =</span> x, <span class="at">data =</span> tas_bd) <span class="sc">%&gt;%</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">solve</span>()</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="do">## return data frame with solution</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">s =</span> s<span class="sc">$</span>solution_1)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(s) <span class="ot">&lt;-</span> <span class="fu">with_options</span>(<span class="fu">list</span>(<span class="at">scipen =</span> <span class="dv">30</span>), <span class="fu">paste0</span>(<span class="st">&quot;penalty_&quot;</span>, x))</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  s</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="co"># format results as a single spatial object</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>blended_results <span class="ot">&lt;-</span> <span class="fu">cbind</span>(tas_pu, <span class="fu">do.call</span>(bind_cols, blended_results))</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plot maps of prioritizations</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    blended_results <span class="sc">%&gt;%</span></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;penalty_&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(is.numeric, <span class="cf">function</span>(x) {</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>        blended_results<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;locked in&quot;</span>,</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>        x <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;priority&quot;</span>,</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;other&quot;</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>    }),</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">pal =</span> <span class="fu">c</span>(<span class="st">&quot;purple&quot;</span>, <span class="st">&quot;grey90&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We now have a set of candidate prioritizations generated using the blended approach. The main advantages of this approach is that it is similar calibration analyses used by other decision support tools for conservation (i.e., <em>Marxan</em>) and it is relatively straightforward to implement. However, this approach also has a key disadvantage. Because the <code>penalty</code> parameter is a unitless trade-off parameter – meaning that we can’t leverage existing knowledge to specify a suitable range of <code>penalty</code> values – we first have to conduct a preliminary analysis to identify an upper limit. Although finding an upper limit was fairly simple for the example dataset, it can be difficult to find for more realistic data. In the next section, we will show how to generate a set of candidate prioritizations using the hierarchical approach – which does not have this disadvantage.</p>
</div>
<div id="hierarchical-approach" class="section level3">
<h3>Hierarchical approach</h3>
<p>The hierarchical approach for multi-objective optimization involves generating a series of incremental prioritizations – using a different objective at each increment to refine the previous solution – until the final solution achieves all of the objectives. The advantage with this approach is that we can specify trade-off parameters for each objective based on a percentage from optimality. This means that we can leverage our own knowledge – or that of decision maker – to generate a range of suitable trade-off parameters. As such, this approach does not require us to generate a series of preliminary prioritizations.</p>
<p>This approach is slightly more complicated to implement within the <em>prioritizr R</em> package then the blended approach. To start off, we generate an initial prioritization based on a problem formulation that does not consider any penalties. Critically, we will generate this prioritization by solving the problem to optimality (using the <code>gap</code> parameter of the <code>add_default_solver()</code> function).</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a problem without boundary penalties</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_default_solver</span>(<span class="at">gap =</span> <span class="dv">0</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># solve problem</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">solve</span>(p1)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># add column for making a map of the prioritization</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>s1<span class="sc">$</span>map_1 <span class="ot">&lt;-</span> <span class="fu">case_when</span>(</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  s1<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;locked in&quot;</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  s1<span class="sc">$</span>solution_1 <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;priority&quot;</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;other&quot;</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plot map of prioritization</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  s1[, <span class="st">&quot;map_1&quot;</span>], <span class="at">pal =</span> <span class="fu">c</span>(<span class="st">&quot;purple&quot;</span>, <span class="st">&quot;grey90&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>),</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="cn">NULL</span>, <span class="at">key.pos =</span> <span class="dv">1</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-15-1.png" width="336" style="display: block; margin: auto;" /></p>
<p>Next, we will calculate the total cost of the initial prioritization.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate cost</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>s1_cost <span class="ot">&lt;-</span> <span class="fu">eval_cost_summary</span>(p1, s1[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>cost</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print cost</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(s1_cost)</span></code></pre></div>
<pre><code>## [1] 354.3258</code></pre>
<p>Now we will calculate a series of cost thresholds. These cost thresholds will be calculated by inflating the cost of the initial prioritization by a range of percentage values. Since these values are percentages – and not unitless values unlike those used in the blended approach – we can use domain knowledge to specify a suitable range of cost thresholds. For this tutorial, let’s assume that it would be impractical – per our domain knowledge – to expend more than four times the total cost of the initial prioritization to reduce spatial fragmentation.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate cost threshold values</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> s1_cost <span class="sc">+</span> (s1_cost <span class="sc">*</span> <span class="fu">seq</span>(<span class="fl">1e-5</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">9</span>))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(threshold)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print cost thresholds</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(threshold)</span></code></pre></div>
<pre><code>## [1]  355  532  709  886 1063 1241 1418 1595 1772</code></pre>
<p>After generating the cost thresholds, we can use them to generate prioritizations. Specifically, we will generate prioritizations that aim to minimize total boundary length as much as possible – ignoring the total cost of the prioritizations – whilst ensuring that the total cost of the prioritization does not exceed a given cost threshold and the other considerations (e.g., locked in constraints). To achieve this, we create a new column in the <code>tas_pu</code> object that contains only zero values (called <code>zeros</code>) and use this new column to specify the cost data for the prioritizations. <strong>Although we normally recommend against cost data that contain zero values – because planning units with zero costs are often selected in prioritizations even if they are not needed – here we use zero cost values so that the prioritization will focus exclusively on spatial fragmentation.</strong> Additionally, when it comes to generating the prioritization, we will add linear constraints to ensure that the total cost of the prioritization does not exceed a given cost threshold (using the <code>add_linear_constraints()</code> function).</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add a column with zeros</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>tas_pu<span class="sc">$</span>zeros <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># define a problem with zero cost values and boundary penalties</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="do">## note that because all the costs are all zero, it doesn&#39;t actually</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="do">## matter what penalty value is used (as long as the value is &gt; 0)</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="do">## and so we just use a value of 1</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;zeros&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_boundary_penalties</span>(<span class="at">penalty =</span> <span class="dv">1</span>, <span class="at">data =</span> tas_bd) <span class="sc">%&gt;%</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>()</span></code></pre></div>
<pre><code>## Warning: [1m[22m`x[, cost_column]` has only zero values.</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate prioritizations based on each cost threshold</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="do">## note that the prioritizations are solved to within 10% of optimality</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="do">## (the default gap) because the gap is not specified</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>hierarchical_results <span class="ot">&lt;-</span> <span class="fu">lapply</span>(threshold, <span class="cf">function</span>(x) {</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="do">## generate solution by adding a constraint based on the threshold and</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## using the &quot;real&quot; cost values (i.e., not zeros)</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    p2 <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_linear_constraints</span>(<span class="at">threshold =</span> x, <span class="at">sense =</span> <span class="st">&quot;&lt;=&quot;</span>, <span class="at">data =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">solve</span>()</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="do">## return data frame with solution</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">s =</span> s<span class="sc">$</span>solution_1)</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(s) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;threshold_&quot;</span>, x)</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  s</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a><span class="co"># format results as a single spatial object</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>hierarchical_results <span class="ot">&lt;-</span> <span class="fu">cbind</span>(tas_pu, <span class="fu">do.call</span>(bind_cols, hierarchical_results))</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plot maps of prioritizations</span></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    hierarchical_results <span class="sc">%&gt;%</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;threshold_&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(is.numeric, <span class="cf">function</span>(x) {</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>        hierarchical_results<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;locked in&quot;</span>,</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>        x <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;priority&quot;</span>,</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;other&quot;</span></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>    }),</span>
<span id="cb29-32"><a href="#cb29-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">pal =</span> <span class="fu">c</span>(<span class="st">&quot;purple&quot;</span>, <span class="st">&quot;grey90&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)</span>
<span id="cb29-33"><a href="#cb29-33" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We now have a set of candidate prioritizations generated using the hierarchical approach. This approach can be much faster than the blended approach because it does not require generating a set of prioritizations to identify an upper limit for the <code>penalty</code> trade-off parameter. After generating a set of candidate prioritizations, we can then calculate performance metrics to compare the prioritizations.</p>
</div>
</div>
<div id="calculating-performance-metrics" class="section level2">
<h2>Calculating performance metrics</h2>
<p>Here we will calculate performance metrics to compare the prioritizations. Since we aim to navigate trade-offs between the total cost of a prioritization and the overall level of spatial fragmentation associated with a prioritization (as measured by total boundary length), we will calculate metrics to assess these criteria. Although we generated two sets of candidate prioritizations in the previous section; for brevity, here we will consider the candidate prioritizations generated using the hierarchical approach. <strong>Please note that you could also apply the following procedures to candidate prioritizations generated using the blended approach.</strong></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate metrics for prioritizations</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="do">## note that we use p0 and not p1 so that cost calculations are based</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="do">## on the cost values and not zeros</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>hierarchical_metrics <span class="ot">&lt;-</span> <span class="fu">lapply</span>(</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">grep</span>(<span class="st">&quot;threshold_&quot;</span>, <span class="fu">names</span>(hierarchical_results)), <span class="cf">function</span>(x) {</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> hierarchical_results[, x]</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">data.frame</span>(</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">total_cost =</span> <span class="fu">eval_cost_summary</span>(p0, x)<span class="sc">$</span>cost,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">total_boundary_length =</span> <span class="fu">eval_boundary_summary</span>(p0, x)<span class="sc">$</span>boundary</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>hierarchical_metrics <span class="ot">&lt;-</span> <span class="fu">do.call</span>(bind_rows, hierarchical_metrics)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>hierarchical_metrics<span class="sc">$</span>threshold <span class="ot">&lt;-</span> threshold</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>hierarchical_metrics <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(hierarchical_metrics)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a><span class="co"># preview metrics</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(hierarchical_metrics)</span></code></pre></div>
<pre><code>## [38;5;246m# A tibble: 9 × 3[39m
##   total_cost total_boundary_length threshold
##        [3m[38;5;246m&lt;dbl&gt;[39m[23m                 [3m[38;5;246m&lt;dbl&gt;[39m[23m     [3m[38;5;246m&lt;dbl&gt;[39m[23m
## [38;5;250m1[39m       355.              2[4m8[24m[4m5[24m[4m7[24m041.       355
## [38;5;250m2[39m       528.              2[4m3[24m[4m0[24m[4m0[24m878.       532
## [38;5;250m3[39m       706.              2[4m1[24m[4m2[24m[4m9[24m475.       709
## [38;5;250m4[39m       880.              2[4m0[24m[4m1[24m[4m2[24m381.       886
## [38;5;250m5[39m      [4m1[24m061.              1[4m9[24m[4m4[24m[4m5[24m769.      [4m1[24m063
## [38;5;250m6[39m      [4m1[24m240.              1[4m8[24m[4m8[24m[4m9[24m002.      [4m1[24m241
## [38;5;250m7[39m      [4m1[24m415.              1[4m8[24m[4m2[24m[4m8[24m894.      [4m1[24m418
## [38;5;250m8[39m      [4m1[24m594.              1[4m7[24m[4m8[24m[4m6[24m337.      [4m1[24m595
## [38;5;250m9[39m      [4m1[24m769.              1[4m7[24m[4m3[24m[4m0[24m507.      [4m1[24m772</code></pre>
<p>After calculating the metrics, let’s we can use them to help select a prioritization.</p>
</div>
<div id="selecting-a-prioritization" class="section level2">
<h2>Selecting a prioritization</h2>
<p>Now we need to decide on which candidate prioritization achieves the best trade-off. There are a range of qualitative and quantitative methods that are available to select a candidate prioritization <span class="citation">(Ardron <em>et al.</em> 2010)</span>. Here we will consider three different methods. Since some of these methods use a set of candidate prioritizations, we will use the candidate prioritizations using the hierarchical approach for these methods. To keep track of the prioritizations selected by different methods, let’s create a <code>results_data</code> table.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create data for plotting</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>result_data <span class="ot">&lt;-</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  hierarchical_metrics <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="do">## rename threshold column to value column</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">value =</span> <span class="st">&quot;threshold&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## add column with column names that contain candidate prioritizations</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">grep</span>(</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">&quot;threshold_&quot;</span>, <span class="fu">names</span>(hierarchical_results), <span class="at">value =</span> <span class="cn">TRUE</span>, <span class="at">fixed =</span> <span class="cn">TRUE</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="do">## add column with labels for plotting</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label =</span> <span class="fu">paste</span>(<span class="st">&quot;Threshold =&quot;</span>, value)) <span class="sc">%&gt;%</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="do">## add column to keep track prioritizations selected by different methods</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">method =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># print table</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_data)</span></code></pre></div>
<pre><code>## [38;5;246m# A tibble: 9 × 6[39m
##   total_cost total_boundary_length value name           label            method
##        [3m[38;5;246m&lt;dbl&gt;[39m[23m                 [3m[38;5;246m&lt;dbl&gt;[39m[23m [3m[38;5;246m&lt;dbl&gt;[39m[23m [3m[38;5;246m&lt;chr&gt;[39m[23m          [3m[38;5;246m&lt;chr&gt;[39m[23m            [3m[38;5;246m&lt;chr&gt;[39m[23m 
## [38;5;250m1[39m       355.              2[4m8[24m[4m5[24m[4m7[24m041.   355 threshold_355  Threshold = 355  none  
## [38;5;250m2[39m       528.              2[4m3[24m[4m0[24m[4m0[24m878.   532 threshold_532  Threshold = 532  none  
## [38;5;250m3[39m       706.              2[4m1[24m[4m2[24m[4m9[24m475.   709 threshold_709  Threshold = 709  none  
## [38;5;250m4[39m       880.              2[4m0[24m[4m1[24m[4m2[24m381.   886 threshold_886  Threshold = 886  none  
## [38;5;250m5[39m      [4m1[24m061.              1[4m9[24m[4m4[24m[4m5[24m769.  [4m1[24m063 threshold_1063 Threshold = 1063 none  
## [38;5;250m6[39m      [4m1[24m240.              1[4m8[24m[4m8[24m[4m9[24m002.  [4m1[24m241 threshold_1241 Threshold = 1241 none  
## [38;5;250m7[39m      [4m1[24m415.              1[4m8[24m[4m2[24m[4m8[24m894.  [4m1[24m418 threshold_1418 Threshold = 1418 none  
## [38;5;250m8[39m      [4m1[24m594.              1[4m7[24m[4m8[24m[4m6[24m337.  [4m1[24m595 threshold_1595 Threshold = 1595 none  
## [38;5;250m9[39m      [4m1[24m769.              1[4m7[24m[4m3[24m[4m0[24m507.  [4m1[24m772 threshold_1772 Threshold = 1772 none</code></pre>
<p>Next, let’s examine some different methods for selecting prioritizations.</p>
<div id="visual-method" class="section level3">
<h3>Visual method</h3>
<p>One qualitative method involves plotting the relationship between the different criteria, and using the plot to visually select a candidate prioritization. This visual method is often used to help calibrate trade-offs among prioritizations generated using the <em>Marxan</em> decision support tool <span class="citation">(e.g., Hermoso <em>et al.</em> 2011; Stewart &amp; Possingham 2005)</span>. So, let’s create a plot to select a prioritization.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create plot to visualize trade-offs and show selected candidate prioritization</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>result_plot <span class="ot">&lt;-</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> result_data,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> total_boundary_length, <span class="at">y =</span> total_cost, <span class="at">label =</span> label)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;visual&quot;</span> <span class="ot">=</span> <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;not selected&quot;</span> <span class="ot">=</span><span class="st">&quot;black&quot;</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total boundary length of prioritization&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Total cost of prioritization&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.4</span>))) <span class="sc">+</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.title =</span> <span class="fu">element_blank</span>())</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a><span class="co"># render plot</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_plot)</span></code></pre></div>
<pre><code>## Warning: [1m[22mNo shared levels found between `names(values)` of the manual scale and the
## data&#39;s [32mcolour[39m values.</code></pre>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We can see that there is a clear relationship between total cost and total boundary length. It would seem that in order to achieve a lower total boundary length – and thus lower spatial fragmentation – the prioritization must have a greater cost. Although we might expect the results to show a smoother curve – in other words, only Pareto dominant solutions – this result is expected because we generated candidate prioritizations using the default optimality gap of 10%. Typically, the visual method involves selecting a prioritization near the elbow of the plot. So, let’s select the prioritization generated using a <code>threshold</code> value of 709. To keep track of the prioritizations selected based on different methods, let’s create a <code>method</code> column in the <code>result_data</code> table.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specify prioritization selected by visual method</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>result_data<span class="sc">$</span>method[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="st">&quot;visual&quot;</span></span></code></pre></div>
<p>Next, let’s consider a quantitative approach.</p>
</div>
<div id="topsis-method" class="section level3">
<h3>TOPSIS method</h3>
<p>Multiple-criteria decision analysis is a discipline that uses analytical methods to evaluate trade-offs between multiple criteria <span class="citation">(MCDA; reviewed in Greene <em>et al.</em> 2011)</span>. Although this discipline contains many different methods, here we will use the the Technique for Order of Preference by Similarity to Ideal Solution (TOPSIS) method <span class="citation">(Hwang &amp; Yoon 1981)</span>. This method requires (i) data describing the performance of each prioritization according to the different criteria, (ii) weights to encode the relative importance of each criteria, and (iii) details on whether each criteria should ideally be minimized or maximized. Let’s run the analysis, assuming that we want equal weighting for total cost and total boundary length.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate TOPSIS scores</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>topsis_results <span class="ot">&lt;-</span> <span class="fu">topsis</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">decision =</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    hierarchical_metrics <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(total_cost, total_boundary_length) <span class="sc">%&gt;%</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.matrix</span>(),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">impacts =</span> <span class="fu">c</span>(<span class="st">&quot;-&quot;</span>, <span class="st">&quot;-&quot;</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(topsis_results)</span></code></pre></div>
<pre><code>##   alt.row     score rank
## 1       1 0.6932024    3
## 2       2 0.7799874    1
## 3       3 0.7324922    2
## 4       4 0.6470149    4
## 5       5 0.5487497    5
## 6       6 0.4589904    6
## 7       7 0.3874544    7
## 8       8 0.3334158    8
## 9       9 0.3067976    9</code></pre>
<p>The candidate prioritization with the greatest TOPSIS score is considered to represent the best trade-off between total cost and total boundary length. So, based on this method, we would select the prioritization generated using a <code>threshold</code> value of 532. Let’s update the <code>result_data</code> with this information.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add column indicating prioritization selected by TOPSIS method</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>result_data<span class="sc">$</span>method[<span class="fu">which.max</span>(topsis_results<span class="sc">$</span>score)] <span class="ot">&lt;-</span> <span class="st">&quot;TOPSIS&quot;</span></span></code></pre></div>
<p>Next, let’s consider another quantitative method.</p>
</div>
<div id="cohon-et-al.-1979-method" class="section level3">
<h3>Cohon <em>et al.</em> (1979) method</h3>
<p>This method is based on an algorithm that was originally developed by Cohon <em>et al.</em> <span class="citation">(Cohon <em>et al.</em> 1979)</span>, and was later adapted for use in systematic conservation planning <span class="citation">(Fischer &amp; Church 2005)</span>. Specifically, it involves generating two ideal prioritizations – with each prioritization representing the ideal prioritization for each criteria – and then using the performance metrics calculated for these prioritizations to automatically derive a trade-off <code>penalty</code> value <span class="citation">(Ardron <em>et al.</em> 2010; Cohon <em>et al.</em> 1979)</span>. Thus, unlike the two other methods, this method does not require a set of candidate prioritizations. <strong>As such, this method can be used to find a prioritization that meets multiple criteria in a much shorter period of time than the other methods.</strong> To implement this method, we first need to generate the ideal prioritizations (note that we specify an gap of 0% to ensure optimality).</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate ideal prioritization based on cost criteria</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="do">## note that this is simply the same as the s1 prioritization we generated</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="do">## for the hierarchical approach</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_default_solver</span>(<span class="at">gap =</span> <span class="dv">0</span>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># solve problem</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>s3 <span class="ot">&lt;-</span> <span class="fu">solve</span>(p3)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="co"># generate ideal prioritization based on spatial fragmentation criteria</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="do">## note that any non-zero penalty value would here,</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="do">## so we just use a penalty  of 1</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;zeros&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_boundary_penalties</span>(<span class="at">penalty =</span> <span class="dv">1</span>, <span class="at">data =</span> tas_bd) <span class="sc">%&gt;%</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_default_solver</span>(<span class="at">gap =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## Warning: [1m[22m`x[, cost_column]` has only zero values.</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># solve problem</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>s4 <span class="ot">&lt;-</span> <span class="fu">solve</span>(p4)</span></code></pre></div>
<p>Next, let’s calculate the performance metrics for these prioritizations.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate problem formulation with costs and boundary penalties for</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># calculating performance metrics</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_boundary_penalties</span>(<span class="at">penalty =</span> <span class="dv">1</span>, <span class="at">data =</span> tas_bd) <span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>()</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate performance metrics for ideal cost prioritization</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>s3_metrics <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_cost =</span> <span class="fu">eval_cost_summary</span>(p5, s3[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>cost,</span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_boundary_length =</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">eval_boundary_summary</span>(p5, s3[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>boundary</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate performance metrics for ideal boundary length prioritization</span></span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>s4_metrics <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_cost =</span> <span class="fu">eval_cost_summary</span>(p5, s4[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>cost,</span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_boundary_length =</span></span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">eval_boundary_summary</span>(p5, s4[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>boundary</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>After calculating these performance metrics, we can use them to automatically calculate a <code>penalty</code> value.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate penalty value based on Cohon et al. 1979</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>cohon_penalty <span class="ot">&lt;-</span> <span class="fu">abs</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  (s3_metrics<span class="sc">$</span>total_cost <span class="sc">-</span> s4_metrics<span class="sc">$</span>total_cost) <span class="sc">/</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  (s3_metrics<span class="sc">$</span>total_boundary_length <span class="sc">-</span> s4_metrics<span class="sc">$</span>total_boundary_length)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># round to 5 decimal places to avoid numerical issues during optimization</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>cohon_penalty <span class="ot">&lt;-</span> <span class="fu">round</span>(cohon_penalty, <span class="dv">5</span>)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># print penalty value</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cohon_penalty)</span></code></pre></div>
<pre><code>## [1] 0.00902</code></pre>
<p>Now that we have calculated a <code>penalty</code> value using this method, we can use it to generate a prioritization.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate prioritization using penalty value calculated using Cohon et al. 1979</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">problem</span>(tas_pu, tas_features, <span class="at">cost_column =</span> <span class="st">&quot;cost&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_min_set_objective</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_boundary_penalties</span>(<span class="at">penalty =</span> cohon_penalty, <span class="at">data =</span> tas_bd) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_relative_targets</span>(<span class="fl">0.17</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_locked_in_constraints</span>(<span class="st">&quot;locked_in&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_binary_decisions</span>()</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="co"># solve problem</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>s6 <span class="ot">&lt;-</span> <span class="fu">solve</span>(p6)</span></code></pre></div>
<p>Let’s update the <code>results_data</code> table with results about the prioritization.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add new row with data for prioritization generated following Cohon et al. 1979</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>result_data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  result_data,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cost =</span> <span class="fu">eval_cost_summary</span>(p6, s6[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>cost,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_boundary_length =</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">eval_boundary_summary</span>(p6, s6[, <span class="st">&quot;solution_1&quot;</span>])<span class="sc">$</span>boundary,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> cohon_penalty,</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="fu">paste0</span>(<span class="st">&quot;penalty_&quot;</span>, cohon_penalty),</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">&quot;Penalty = &quot;</span>,  cohon_penalty),</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;Cohon&quot;</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Next, let’s compare the prioritizations selected by different methods.</p>
</div>
<div id="method-comparison" class="section level3">
<h3>Method comparison</h3>
<p>Let’s create a plot to visualize the results from the different methods.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create plot to visualize trade-offs and show selected candidate prioritization</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>result_plot <span class="ot">&lt;-</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>      result_data <span class="sc">%&gt;%</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">vjust =</span> <span class="fu">if_else</span>(method <span class="sc">==</span> <span class="st">&quot;Cohon&quot;</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="fl">0.5</span>)),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> total_boundary_length, <span class="at">y =</span> total_cost, <span class="at">label =</span> label)</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> method), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">vjust =</span> vjust, <span class="at">color =</span> method), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Method&quot;</span>,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;visual&quot;</span> <span class="ot">=</span> <span class="st">&quot;#984ea3&quot;</span>,</span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;none&quot;</span> <span class="ot">=</span> <span class="st">&quot;#000000&quot;</span>,</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;TOPSIS&quot;</span> <span class="ot">=</span> <span class="st">&quot;#e41a1c&quot;</span>,</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;Cohon&quot;</span> <span class="ot">=</span> <span class="st">&quot;#377eb8&quot;</span></span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total boundary length of prioritization&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Total cost of prioritization&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.4</span>)))</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a><span class="co"># render plot</span></span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result_plot)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-30-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We can see that the different methods selected different prioritizations. To further compare the results from the different methods, let’s create some maps showing the selected prioritizations.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract column names for creating the prioritizations</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>visual_name <span class="ot">&lt;-</span> result_data<span class="sc">$</span>name[[<span class="fu">which</span>(result_data<span class="sc">$</span>method <span class="sc">==</span> <span class="st">&quot;visual&quot;</span>)]]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>topsis_name <span class="ot">&lt;-</span> result_data<span class="sc">$</span>name[[<span class="fu">which</span>(result_data<span class="sc">$</span>method <span class="sc">==</span> <span class="st">&quot;TOPSIS&quot;</span>)]]</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create object with selected prioritizations</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>solutions  <span class="ot">&lt;-</span> <span class="fu">bind_cols</span>(</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  tas_pu,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  hierarchical_results <span class="sc">%&gt;%</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(visual_name, topsis_name))) <span class="sc">%&gt;%</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">&quot;Visual&quot;</span>, <span class="st">&quot;TOPSIS&quot;</span>)),</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  s6 <span class="sc">%&gt;%</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(solution_1) <span class="sc">%&gt;%</span></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">Cohon =</span> <span class="st">&quot;solution_1&quot;</span>)</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a><span class="co"># plot maps of selected prioritizations</span></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb49-20"><a href="#cb49-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span></span>
<span id="cb49-21"><a href="#cb49-21" aria-hidden="true" tabindex="-1"></a>    solutions <span class="sc">%&gt;%</span></span>
<span id="cb49-22"><a href="#cb49-22" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(Visual, TOPSIS, Cohon) <span class="sc">%&gt;%</span></span>
<span id="cb49-23"><a href="#cb49-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate_if</span>(is.numeric, <span class="cf">function</span>(x) {</span>
<span id="cb49-24"><a href="#cb49-24" aria-hidden="true" tabindex="-1"></a>      <span class="fu">case_when</span>(</span>
<span id="cb49-25"><a href="#cb49-25" aria-hidden="true" tabindex="-1"></a>        hierarchical_results<span class="sc">$</span>locked_in <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;locked in&quot;</span>,</span>
<span id="cb49-26"><a href="#cb49-26" aria-hidden="true" tabindex="-1"></a>        x <span class="sc">&gt;</span> <span class="fl">0.5</span> <span class="sc">~</span> <span class="st">&quot;priority&quot;</span>,</span>
<span id="cb49-27"><a href="#cb49-27" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;other&quot;</span></span>
<span id="cb49-28"><a href="#cb49-28" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb49-29"><a href="#cb49-29" aria-hidden="true" tabindex="-1"></a>    }),</span>
<span id="cb49-30"><a href="#cb49-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">pal =</span> <span class="fu">c</span>(<span class="st">&quot;purple&quot;</span>, <span class="st">&quot;grey90&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)</span>
<span id="cb49-31"><a href="#cb49-31" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="calibrating_trade-offs_tutorial_files/figure-html/unnamed-chunk-31-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>How do we determine which one is best? This is difficult to say. Ideally, additional information could be used to help select a prioritization, such as knowledge on available resources, species’ connectivity requirements, and impacts of neighboring land use. However, from a practical perspective, prioritizations generated for academic contexts might find the quantitative approaches more useful because they have greater transparency and reproducibility. Ultimately, all of these methods are designed to support decision making. This means that they are intended to assist the decision making process, not serve as a replacement.</p>
</div>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Hopefully, this vignette has provided a useful introduction for resolving trade-offs in prioritizations. Although we only explored trade-offs between total cost and spatial fragmentation in this tutorial, this analysis could be adapted to explore trade-offs between a wide range of different criteria. For instance, instead of considering total cost as the primary objective, future analyses could explore trade-offs with feature representation (using the <code>add_min_shortfall_objective()</code> function). Additionally, instead of spatial fragmentation, future analyses could explore trade-offs that directly relate to connectivity (using the <code>add_connectivity_penalties()</code> function) or specific variables of interest – such as ecosystem intactness or inverse human footprint index <span class="citation">(Williams <em>et al.</em> 2020; Beyer <em>et al.</em> 2019)</span> – to inform decision making (using the <code>add_linear_penalties()</code> function). Furthermore, after identifying the best <code>penalty</code> or <code>threshold</code> values to strike a balance between multiple criteria, you could generate a portfolio of prioritizations (e.g., using the <code>add_gap_portfolio_function()</code>) to find multiple options for achieving a similar balance. This might be helpful when you need to generate a set of prioritizations that have comparable performance – in terms of how well they achieve different criteria – but select different planning units.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="unnumbered">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-r45" class="csl-entry">
Ardron, J.A., Possingham, H.P. &amp; Klein, C.J. (2010). <em><span>Marxan Good Practices Handbook</span></em>. Pacific Marine Analysis; Research Association, Vancouver, Victoria, BC.
</div>
<div id="ref-r38" class="csl-entry">
Beger, M., Linke, S., Watts, M., Game, E., Treml, E., Ball, I. &amp; Possingham, H.P. (2010). Incorporating asymmetric connectivity into spatial decision making for conservation. <em>Conservation Letters</em>, <em>3</em>, 359–368.
</div>
<div id="ref-r48" class="csl-entry">
Beyer, H.L., Venter, O., Grantham, H.S. &amp; Watson, J.E.M. (2019). Substantial losses in ecoregion intactness highlight urgency of globally coordinated action. <em>Conservation Letters</em>, <em>13</em>.
</div>
<div id="ref-r49" class="csl-entry">
Cohon, J.L., Church, R.L. &amp; Sheer, D.P. (1979). Generating multiobjective trade-offs: An algorithm for bicriterion problems. <em>Water Resources Research</em>, <em>15</em>, 1001–1010.
</div>
<div id="ref-r40" class="csl-entry">
Dorji, T., Linke, S. &amp; Sheldon, F. (2020). Freshwater conservation planning in the context of nature needs half and protected area dynamism in bhutan. <em>Biological Conservation</em>, <em>251</em>, 108785.
</div>
<div id="ref-r50" class="csl-entry">
Fischer, D.T. &amp; Church, R.L. (2005). The <span>SITES</span> reserve selection system: A critical review. <em>Environmental Modeling and Assessment</em>, <em>10</em>, 215–228.
</div>
<div id="ref-r44" class="csl-entry">
Greene, R., Devillers, R., Luther, J.E. &amp; Eddy, B.G. (2011). <span>GIS</span>-based multiple-criteria decision analysis. <em>Geography Compass</em>, <em>5</em>, 412–432.
</div>
<div id="ref-r39" class="csl-entry">
Hermoso, V., Cattarino, L., Linke, S. &amp; Kennard, M.J. (2018). Catchment zoning to enhance co-benefits and minimize trade-offs between ecosystem services and freshwater biodiversity conservation. <em>Aquatic Conservation: Marine and Freshwater Ecosystems</em>, <em>28</em>, 1004–1014.
</div>
<div id="ref-r43" class="csl-entry">
Hermoso, V., Kennard, M.J. &amp; Linke, S. (2012). Integrating multidirectional connectivity requirements in systematic conservation planning for freshwater systems. <em>Diversity and Distributions</em>, <em>18</em>, 448–458.
</div>
<div id="ref-r41" class="csl-entry">
Hermoso, V., Linke, S., Prenda, J. &amp; Possingham, H.P. (2011). Addressing longitudinal connectivity in the systematic conservation planning of fresh waters. <em>Freshwater Biology</em>, <em>56</em>, 57–70.
</div>
<div id="ref-r46" class="csl-entry">
Hwang, C.L. &amp; Yoon, K.G. (1981). <em><span class="nocase">Multiple Attribute Decision Making: Methods and Applications</span></em>. Springer-Verlag, New York, NY.
</div>
<div id="ref-r37" class="csl-entry">
Klein, C.J., Tulloch, V.J., Halpern, B.S., Selkoe, K.A., Watts, M.E., Steinback, C., Scholz, A. &amp; Possingham, H.P. (2013). Tradeoffs in marine reserve design: Habitat condition, representation, and socioeconomic costs. <em>Conservation Letters</em>, 324–332.
</div>
<div id="ref-r4" class="csl-entry">
Margules, C.R. &amp; Pressey, R.L. (2000). Systematic conservation planning. <em>Nature</em>, <em>405</em>, 243–253.
</div>
<div id="ref-r42" class="csl-entry">
Stewart, R.R. &amp; Possingham, H.P. (2005). Efficiency, costs and trade-offs in marine reserve system design. <em>Environmental Modeling and Assessment</em>, <em>10</em>, 203–213.
</div>
<div id="ref-r36" class="csl-entry">
Vane-Wright, R.I., Humphries, C.J. &amp; Williams, P.H. (1991). What to protect? — <span>Systematics</span> and the agony of choice. <em>Biological Conservation</em>, <em>55</em>, 235–254.
</div>
<div id="ref-r47" class="csl-entry">
Williams, B.A., Venter, O., Allan, J.R., Atkinson, S.C., Rehbein, J.A., Ward, M., Marco, M.D., Grantham, H.S., Ervin, J., Goetz, S.J., Hansen, A.J., Jantz, P., Pillay, R., Rodrı́guez-Buriticá, S., Supples, C., Virnig, A.L.S. &amp; Watson, J.E.M. (2020). Change in terrestrial human footprint drives continued loss of intact ecosystems. <em>One Earth</em>, <em>3</em>, 371–382.
</div>
</div>
</div>
  </main><aside class="col-md-3"><nav id="toc"><h2>On this page</h2>
    </nav></aside></div>



    <footer><div class="pkgdown-footer-left">
  <p></p><p>Developed by <a href="https://jeffrey-hanson.com" class="external-link">Jeffrey O Hanson</a>, <a href="http://www.richard-schuster.com" class="external-link">Richard Schuster</a>, Nina Morrell, <a href="http://strimas.com" class="external-link">Matthew Strimas-Mackey</a>, Brandon P M Edwards, Matthew E Watts, <a href="https://arcese.forestry.ubc.ca" class="external-link">Peter Arcese</a>, <a href="https://josephrbennett.wordpress.com" class="external-link">Joseph Bennett</a>, <a href="http://www.possinghamlab.org" class="external-link">Hugh P Possingham</a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p></p><p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.0.7.</p>
</div>

    </footer></div>

  

  

  </body></html>
