# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_new_optimization_problem <- function(nrow = 1000000L, ncol = 1000000L, ncell = 100000L) {
    .Call(`_prioritizr_rcpp_new_optimization_problem`, nrow, ncol, ncell)
}

rcpp_predefined_optimization_problem <- function(l) {
    .Call(`_prioritizr_rcpp_predefined_optimization_problem`, l)
}

rcpp_optimization_problem_as_list <- function(x) {
    .Call(`_prioritizr_rcpp_optimization_problem_as_list`, x)
}

rcpp_get_optimization_problem_ncol <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_ncol`, x)
}

rcpp_get_optimization_problem_nrow <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_nrow`, x)
}

rcpp_get_optimization_problem_ncell <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_ncell`, x)
}

rcpp_get_optimization_problem_A <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_A`, x)
}

rcpp_get_optimization_problem_modelsense <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_modelsense`, x)
}

rcpp_get_optimization_problem_number_of_planning_units <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_number_of_planning_units`, x)
}

rcpp_get_optimization_problem_number_of_features <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_number_of_features`, x)
}

rcpp_get_optimization_problem_number_of_zones <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_number_of_zones`, x)
}

rcpp_get_optimization_problem_vtype <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_vtype`, x)
}

rcpp_get_optimization_problem_obj <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_obj`, x)
}

rcpp_get_optimization_problem_rhs <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_rhs`, x)
}

rcpp_get_optimization_problem_sense <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_sense`, x)
}

rcpp_get_optimization_problem_lb <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_lb`, x)
}

rcpp_get_optimization_problem_ub <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_ub`, x)
}

rcpp_get_optimization_problem_col_ids <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_col_ids`, x)
}

rcpp_get_optimization_problem_row_ids <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_row_ids`, x)
}

rcpp_get_optimization_problem_compressed_formulation <- function(x) {
    .Call(`_prioritizr_rcpp_get_optimization_problem_compressed_formulation`, x)
}

rcpp_set_optimization_problem_shuffled <- function(x) {
    .Call(`_prioritizr_rcpp_set_optimization_problem_shuffled`, x)
}

rcpp_add_rij_data <- function(x, rij_list, targets_list, compressed_formulation) {
    .Call(`_prioritizr_rcpp_add_rij_data`, x, rij_list, targets_list, compressed_formulation)
}

rcpp_add_zones_constraints <- function(x) {
    .Call(`_prioritizr_rcpp_add_zones_constraints`, x)
}

rcpp_apply_boundary_penalties <- function(x, penalty, edge_factor, zones_matrix, boundary_matrix) {
    .Call(`_prioritizr_rcpp_apply_boundary_penalties`, x, penalty, edge_factor, zones_matrix, boundary_matrix)
}

rcpp_apply_connected_constraints <- function(x, connected_matrix) {
    .Call(`_prioritizr_rcpp_apply_connected_constraints`, x, connected_matrix)
}

rcpp_apply_connectivity_penalties <- function(x, penalty, data) {
    .Call(`_prioritizr_rcpp_apply_connectivity_penalties`, x, penalty, data)
}

rcpp_apply_corridor_constraints <- function(x, connected_matrix_list, threshold) {
    .Call(`_prioritizr_rcpp_apply_corridor_constraints`, x, connected_matrix_list, threshold)
}

rcpp_apply_decisions <- function(x, vtype, default_lower, default_upper) {
    .Call(`_prioritizr_rcpp_apply_decisions`, x, vtype, default_lower, default_upper)
}

rcpp_apply_feature_weights <- function(x, weights) {
    .Call(`_prioritizr_rcpp_apply_feature_weights`, x, weights)
}

rcpp_apply_locked_constraints <- function(x, pu, zone, status) {
    .Call(`_prioritizr_rcpp_apply_locked_constraints`, x, pu, zone, status)
}

rcpp_apply_max_cover_objective <- function(x, costs, budget) {
    .Call(`_prioritizr_rcpp_apply_max_cover_objective`, x, costs, budget)
}

rcpp_apply_max_features_objective <- function(x, targets_list, costs, budget) {
    .Call(`_prioritizr_rcpp_apply_max_features_objective`, x, targets_list, costs, budget)
}

rcpp_apply_max_phylo_objective <- function(x, targets_list, costs, budget, branch_matrix, branch_lengths) {
    .Call(`_prioritizr_rcpp_apply_max_phylo_objective`, x, targets_list, costs, budget, branch_matrix, branch_lengths)
}

rcpp_apply_max_utility_objective <- function(x, abundances, costs, budget) {
    .Call(`_prioritizr_rcpp_apply_max_utility_objective`, x, abundances, costs, budget)
}

rcpp_apply_min_set_objective <- function(x, targets_list, costs) {
    .Call(`_prioritizr_rcpp_apply_min_set_objective`, x, targets_list, costs)
}

rcpp_apply_neighbor_constraints <- function(x, connected_data, k) {
    .Call(`_prioritizr_rcpp_apply_neighbor_constraints`, x, connected_data, k)
}

rcpp_boundary_data <- function(data, tolerance = 0.00001) {
    .Call(`_prioritizr_rcpp_boundary_data`, data, tolerance)
}

rcpp_branch_matrix <- function(x) {
    .Call(`_prioritizr_rcpp_branch_matrix`, x)
}

rcpp_forbid_solution <- function(x, solution) {
    .Call(`_prioritizr_rcpp_forbid_solution`, x, solution)
}

rcpp_list_to_matrix_indices <- function(x, n_preallocate = 10000L) {
    .Call(`_prioritizr_rcpp_list_to_matrix_indices`, x, n_preallocate)
}

rcpp_sp_to_polyset <- function(x, slot, n_preallocate = 10000L) {
    .Call(`_prioritizr_rcpp_sp_to_polyset`, x, slot, n_preallocate)
}

